<script lang="ts">
	import { page } from '$app/stores';
	import type { Locale } from '$lib/i18n';

	$: lang = ($page.params.lang || 'en') as Locale;

	const SITE_NAME = 'SDK.ac';
	const SITE_DOMAIN = 'sdk.ac';
	const CONTACT_EMAIL = 'contact@sdk.ac';
	const COMPANY_NAME = 'SDK Co., Ltd.';
	const COMPANY_ADDRESS = '제주특별자치도 제주시 남성로 127, 4층';
	const COMPANY_ADDRESS_EN = '4F, 127 Namseong-ro, Jeju-si, Jeju Special Self-Governing Province, Republic of Korea';
	const ADS_OPTOUT_URL = 'https://www.google.com/settings/ads';
	const EFFECTIVE_DATE = '2025-01-15';
	const LAST_UPDATED = '2026-07-02';

	type PrivacyContent = {
		title: string;
		lastUpdated: string;
		effective: string;
		intro: string;
		sections: { title: string; content: string }[];
	};

	const content: Partial<Record<Locale, PrivacyContent>> & { en: PrivacyContent } = {
		en: {
			title: 'Privacy Policy',
			lastUpdated: `Last Updated: ${LAST_UPDATED}`,
			effective: `Effective Date: ${EFFECTIVE_DATE}`,
			intro: `${COMPANY_NAME} ("Company", "we", "our", "us"), the operator of ${SITE_NAME} (the "Service"), respects your privacy and is committed to handling personal data lawfully, fairly, and transparently. This Privacy Policy describes what information we collect, how we use it, the third parties we share it with, your rights under applicable laws — including the Personal Information Protection Act of the Republic of Korea ("PIPA") and the EU General Data Protection Regulation ("GDPR") — and how to exercise those rights. By accessing or using ${SITE_NAME}, you acknowledge that you have read and understood this Policy.`,
			sections: [
				{ title: '1. Scope of this Policy', content: `This Policy applies to the website hosted at https://${SITE_DOMAIN}, all subdomains, and any associated services we operate (collectively, the "Service"). It does not apply to third-party websites, AI assistants, or advertisers that we link to or that may appear in advertising served on the Service. In particular, when you copy a prompt generated by one of our tools and paste it into a third-party AI service (such as ChatGPT, Claude, or Gemini), your use of that service is governed exclusively by that provider's own privacy policy. We encourage you to review the privacy notices of those third parties before providing them with personal data.` },
				{ title: '2. Personal Information We Collect', content: `We have intentionally designed ${SITE_NAME} to collect as little personal data as possible. Specifically:

- **Account Data**: ${SITE_NAME} does not require an account. There is no sign-up flow, no e-mail collection, and no password. We therefore hold no account records about you.
- **Tool Inputs**: Text, code, or other content you enter into a tool is processed in your browser (see Section 3). We do not transmit, log, or store the contents of your inputs on our servers.
- **Preferences**: Your theme and language choices are stored only in your browser's localStorage and never reach our infrastructure.
- **Analytics Data (automatic)**: Aggregated, pseudonymised metrics such as page views, referring URL, approximate country (derived from a truncated IP address), browser family, operating system, screen size, and language preference.
- **Advertising Data**: Cookies and similar identifiers set by Google AdSense as described in Section 7.
- **Diagnostic Logs**: Cloudflare, our edge provider, automatically logs HTTP request metadata (timestamp, method, path, response status, edge location, anonymised IP) for a short retention window for security, abuse prevention, and capacity planning.
- **Communication Data**: When you contact us by e-mail, we receive your e-mail address, the content of your message, and any attachments you choose to send.

We do not knowingly collect special categories of personal data (e.g., health, religion, biometrics), government identifiers, payment-card numbers, or precise geolocation.` },
				{ title: '3. How Text You Submit to Our AI Tools Is Processed', content: `This section addresses the question users most often ask us: what happens to the text I type into a tool?

- **Processing happens on your device.** Our tools (AI translator, text summarizer, prompt generator, image prompt builder, code explainer, email writer, hashtag generator, writing assistant) run their logic in your browser. The text you enter is used transiently in your device's memory to produce the output, and is discarded when you clear the input or leave the page.
- **We do not store your text.** No tool input is transmitted to, logged by, or stored permanently on our servers. There is no server-side database of user text.
- **We do not train on your text.** Your inputs are never used to train, fine-tune, or evaluate any machine-learning model, by us or on our behalf.
- **Third-party AI services are your choice.** Where a tool generates a prompt intended for an external AI assistant, the prompt leaves your device only when you yourself copy it and paste it into that assistant. From that point, the processing of the text — including any transmission to an AI model API and any retention — is governed by the third-party provider's terms and privacy policy, not this one. If we ever introduce a tool that sends your text to an AI model API directly, we will say so clearly on the tool page before you submit anything, transmit the text over encrypted connections solely to generate your result, and not store it permanently.` },
				{ title: '4. Purposes of Use and Legal Bases', content: `We use the limited information we collect for the following purposes, each tied to a legal basis under GDPR and a lawful ground under PIPA:

- **Providing the Service** (performance of a contract / legitimate interest): rendering pages, executing tool logic in your browser, and delivering assets through our CDN.
- **Securing the Service** (legitimate interest): detecting and mitigating abuse, denial-of-service attacks, and scraping using Cloudflare's edge security.
- **Improving the Service** (legitimate interest, with consent where required): aggregated analytics that show us which tools are used, where users get stuck, and which pages are slow.
- **Showing Advertising** (consent / legitimate interest depending on jurisdiction): serving advertisements through Google AdSense to fund the free Service.
- **Responding to You** (consent / legitimate interest): replying to e-mails, bug reports, and business inquiries.
- **Legal Compliance** (legal obligation): meeting requirements under PIPA, GDPR, Korean telecommunications and network laws, and lawful requests from competent authorities.` },
				{ title: '5. Cookies and How to Refuse Them', content: `We use a small number of cookies and browser-storage technologies:

- **Strictly Necessary**: minimal cookies set by our edge provider to balance traffic and mitigate bots. These cannot be disabled if you wish to use the Service.
- **Functional (localStorage)**: theme and language preferences. This data never leaves your device.
- **Analytics**: Google Analytics cookies as described in Section 6.
- **Advertising**: Google AdSense/DoubleClick cookies as described in Section 7.

**You can refuse cookies at any time.** Every major browser lets you block or delete cookies: in Chrome, Settings → Privacy and security → Cookies; in Safari, Preferences → Privacy; in Firefox, Settings → Privacy & Security; in Edge, Settings → Cookies and site permissions. You may also enable tracking protection (Safari ITP, Firefox ETP, Brave Shields). Blocking cookies does not break our tools — they run in your browser regardless — though some preferences may not persist between visits.` },
				{ title: '6. Google Analytics', content: `We use Google Analytics 4, provided by Google LLC, to understand aggregate usage of the Service. Google Analytics uses cookies in the "_ga" family to distinguish visitors; these expire after at most 24 months. We have configured IP anonymisation, do not send tool inputs or any user-generated text to Analytics, and use the data solely in aggregate (e.g., "the summarizer had N visits this week"). Google processes this data on our behalf under its data-processing terms. You can prevent Google Analytics from running by installing the official opt-out browser add-on at https://tools.google.com/dlpage/gaoptout, or by blocking analytics cookies as described in Section 5.` },
				{ title: '7. Google AdSense, DoubleClick Cookies, and Opt-Out', content: `The Service is funded by advertising served through Google AdSense.

- Google, as a third-party vendor, uses cookies — including the DoubleClick (DART) cookie — to serve ads on the Service based on your visits to this and other websites.
- These cookies allow Google and its partners to serve personalised ads, cap ad frequency, and measure ad performance. A list of Google's advertising cookies and their lifetimes is available in Google's advertising privacy documentation.
- **Opt-out**: You may opt out of personalised advertising by visiting Google's Ads Settings at ${ADS_OPTOUT_URL}. You may additionally opt out of many other third-party vendors' personalised ads at https://www.aboutads.info/choices.
- Where required by law (EU, UK, Korea and other jurisdictions), a consent banner is shown before any personalised advertising cookies are set, and you may refuse or later withdraw consent through that banner.
- If you opt out, you will still see ads, but they will not be personalised to your interests.` },
				{ title: '8. Third-Party Processors and International Transfers', content: `We share the minimum necessary information with the following processors, each acting under agreements requiring confidentiality and purpose limitation:

- **Cloudflare, Inc.** — content delivery, DDoS mitigation, edge logging. Data: HTTP request metadata, anonymised IP. Region: global edge network.
- **Google LLC (Google Analytics 4)** — aggregated traffic analytics. Data: anonymised IP, page views, device/browser metadata.
- **Google LLC (Google AdSense)** — advertisement delivery and consent management. Data: advertising cookies, ad interaction events.

We do not sell, rent, or lend your personal data. Some processors operate globally and may process data outside the Republic of Korea or the European Economic Area, including in the United States. Where such transfers occur, we rely on safeguards including Standard Contractual Clauses adopted by the European Commission, the EU-US Data Privacy Framework where applicable, and the cross-border transfer disclosure requirements of PIPA.` },
				{ title: '9. Retention of Personal Information', content: `We retain personal data only for as long as necessary for the purpose for which it was collected:

- **Tool inputs**: not retained at all — they never reach our servers.
- **Preferences (localStorage)**: retained in your browser until you clear them; we never hold a copy.
- **Analytics data**: retained in aggregate form for up to 26 months, after which it is deleted or further anonymised.
- **Edge diagnostic logs**: retained by Cloudflare for a short rolling window (typically under 30 days).
- **E-mail correspondence**: retained for up to 3 years after the last exchange, to maintain context for follow-up inquiries and to satisfy Korean commercial record-keeping requirements, then deleted.

When a statutory retention period under Korean law applies (e.g., records of consumer complaints and dispute resolution: 3 years under the Act on the Consumer Protection in Electronic Commerce), we retain the relevant records for the statutory period only and then destroy them without undue delay.` },
				{ title: '10. Your Rights', content: `Subject to applicable law, you have the right to:

- **Access** the personal data we hold about you and receive a copy;
- **Rectify** inaccurate or incomplete data;
- **Erase** your data ("right to be forgotten") where there is no overriding legal basis for retention;
- **Restrict or object to** processing, including objecting to processing based on legitimate interest;
- **Data portability** — receive data you provided in a structured, machine-readable format;
- **Withdraw consent** at any time, without affecting the lawfulness of processing before withdrawal;
- **Lodge a complaint** with a supervisory authority — in Korea, the Personal Information Protection Commission (privacy.go.kr) or the Korea Internet & Security Agency (KISA, 118); in the EU, your national data protection authority.

Because we deliberately hold almost no personal data, most requests can be satisfied instantly: tool inputs and preferences exist only in your own browser, and clearing your browser's site data removes them completely. For anything else (e.g., deletion of e-mail correspondence), contact us as described in Section 11. We respond to verified requests within the timeframes required by GDPR (one month) and PIPA (10 days for access requests), free of charge except where requests are manifestly unfounded or excessive.` },
				{ title: '11. Privacy Officer and Contact', content: `The Company has designated a privacy officer (개인정보 보호책임자) responsible for handling personal-data inquiries, complaints, and remedies:

- **Privacy Officer**: Privacy Team, ${COMPANY_NAME}
- **E-mail**: ${CONTACT_EMAIL} (include "Legal" or "Privacy" in the subject line)
- **Address**: ${COMPANY_ADDRESS_EN}

We will confirm receipt of privacy inquiries promptly and provide a substantive response within the statutory deadlines. If you believe your inquiry has not been handled adequately, you may contact the Personal Information Protection Commission of Korea (privacy.go.kr / 국번없이 182) or, in the EU, your local supervisory authority.` },
				{ title: '12. Children\'s Privacy', content: `The Service is a general-audience website and is not directed at children under 14 (Korea) or under 16 (EU). We do not knowingly collect personal data from children. Because the Service requires no account and stores no tool inputs, the risk of collecting a child's personal data is inherently minimal. If you believe a child has nevertheless provided us with personal data by e-mail, contact us at ${CONTACT_EMAIL} and we will delete it promptly.` },
				{ title: '13. Security Measures', content: `We take administrative, technical, and physical measures appropriate to the low volume and low sensitivity of the data we handle: all traffic is encrypted with TLS; there is no server-side database of user content that could be breached; internal access to analytics and correspondence is limited to authorised personnel on a need-to-know basis; and our infrastructure providers (Cloudflare, Google) maintain industry-standard certifications including ISO 27001 and SOC 2. No method of transmission over the Internet is 100% secure, but our architecture minimises risk by minimising the data that exists in the first place.` },
				{ title: '14. Changes to this Policy', content: `We may update this Policy to reflect changes in law, technology, or our practices. When we make material changes, we will post the updated Policy on this page at least seven (7) days before it takes effect (thirty (30) days for changes that materially affect your rights), and update the "Last Updated" date at the top. Your continued use of the Service after the effective date of an updated Policy constitutes acknowledgement of the changes. Previous versions are available on request at ${CONTACT_EMAIL}.

This Policy is effective as of ${EFFECTIVE_DATE} and was last updated on ${LAST_UPDATED}.` }
			]
		},

		ko: {
			title: '개인정보 처리방침',
			lastUpdated: `최종 수정일: ${LAST_UPDATED}`,
			effective: `시행일: ${EFFECTIVE_DATE}`,
			intro: `${SITE_NAME}(이하 "서비스")를 운영하는 ${COMPANY_NAME}(이하 "회사")는 이용자의 개인정보를 소중히 여기며, 「개인정보 보호법」(PIPA), EU 「일반 개인정보 보호규정」(GDPR) 등 관련 법령을 준수하여 개인정보를 적법하고 공정하며 투명하게 처리합니다. 본 개인정보 처리방침은 회사가 수집하는 정보, 이용 목적, 제3자 제공, 이용자의 권리와 행사 방법을 규정합니다. ${SITE_NAME}에 접속하거나 이를 이용함으로써 이용자는 본 방침을 읽고 이해하였음을 확인합니다.`,
			sections: [
				{ title: '제1조 (적용 범위)', content: `본 방침은 https://${SITE_DOMAIN} 에서 호스팅되는 웹사이트, 모든 서브도메인 및 회사가 운영하는 관련 서비스(이하 통칭하여 "서비스")에 적용됩니다. 서비스에서 링크되거나 서비스에 게재되는 광고에 나타날 수 있는 제3자 웹사이트, AI 어시스턴트, 광고주에는 적용되지 않습니다. 특히 이용자가 당사 도구가 생성한 프롬프트를 복사하여 제3자 AI 서비스(ChatGPT, Claude, Gemini 등)에 붙여넣는 경우, 해당 서비스 이용에는 해당 사업자의 개인정보처리방침만이 적용됩니다. 제3자에게 개인정보를 제공하기 전에 해당 사업자의 방침을 확인하시기 바랍니다.` },
				{ title: '제2조 (수집하는 개인정보 항목)', content: `회사는 ${SITE_NAME}를 가능한 한 적은 개인정보를 수집하도록 의도적으로 설계했습니다. 구체적으로:

- **계정 정보**: ${SITE_NAME}는 계정이 필요 없습니다. 가입 절차, 이메일 수집, 비밀번호가 없으므로 회사는 이용자에 대한 어떠한 계정 기록도 보유하지 않습니다.
- **도구 입력값**: 도구에 입력하는 텍스트, 코드 등은 이용자의 브라우저에서 처리됩니다(제3조 참조). 회사는 입력 내용을 서버로 전송하거나 기록·저장하지 않습니다.
- **환경설정**: 테마·언어 선택은 이용자 브라우저의 localStorage에만 저장되며 회사 인프라에 도달하지 않습니다.
- **분석 데이터(자동 수집)**: 페이지뷰, 유입 URL, 대략적 국가(단축된 IP 주소에서 도출), 브라우저 종류, 운영체제, 화면 크기, 언어 설정 등 집계·가명화된 지표.
- **광고 데이터**: 제7조에 기재된 Google AdSense가 설정하는 쿠키 및 유사 식별자.
- **진단 로그**: 엣지 사업자인 Cloudflare가 보안, 악용 방지, 용량 계획을 위해 HTTP 요청 메타데이터(시각, 메서드, 경로, 응답 상태, 엣지 위치, 익명화된 IP)를 단기간 자동 기록합니다.
- **커뮤니케이션 데이터**: 이메일로 문의하시는 경우 이메일 주소, 메시지 내용, 첨부파일을 수신합니다.

회사는 민감정보(건강, 종교, 생체정보 등), 고유식별정보, 결제카드 번호, 정밀 위치정보를 수집하지 않습니다.` },
				{ title: '제3조 (AI 도구에 입력한 텍스트의 처리)', content: `이용자가 가장 자주 묻는 질문 — "도구에 입력한 텍스트는 어떻게 되나요?" — 에 대한 조항입니다.

- **처리는 이용자의 기기에서 이루어집니다.** 당사의 도구(AI 번역기, 텍스트 요약기, 프롬프트 생성기, 이미지 프롬프트 빌더, 코드 설명기, 이메일 작성기, 해시태그 생성기, 글쓰기 도우미)는 로직을 이용자의 브라우저에서 실행합니다. 입력한 텍스트는 결과 생성을 위해 기기 메모리에서 일시적으로만 사용되며, 입력을 지우거나 페이지를 떠나면 사라집니다.
- **회사는 텍스트를 저장하지 않습니다.** 어떤 도구 입력값도 회사 서버로 전송·기록되거나 영구 저장되지 않습니다. 이용자 텍스트의 서버측 데이터베이스는 존재하지 않습니다.
- **텍스트를 학습에 사용하지 않습니다.** 이용자의 입력은 회사에 의해서든 회사를 대신해서든 어떠한 기계학습 모델의 학습·미세조정·평가에도 사용되지 않습니다.
- **제3자 AI 서비스는 이용자의 선택입니다.** 도구가 외부 AI 어시스턴트용 프롬프트를 생성하는 경우, 그 프롬프트는 이용자 본인이 직접 복사하여 붙여넣을 때에만 기기를 떠납니다. 그 시점부터 텍스트의 처리 — AI 모델 API로의 전송 및 보관을 포함 — 는 본 방침이 아니라 해당 제3자 사업자의 약관과 개인정보처리방침의 적용을 받습니다. 향후 회사가 이용자의 텍스트를 AI 모델 API로 직접 전송하는 도구를 도입하는 경우, 제출 전에 도구 페이지에 이를 명확히 표시하고, 결과 생성 목적으로만 암호화된 연결을 통해 전송하며, 영구 저장하지 않을 것입니다.` },
				{ title: '제4조 (개인정보의 이용 목적 및 법적 근거)', content: `회사는 수집한 최소한의 정보를 다음 목적으로 이용하며, 각 목적은 GDPR상 법적 근거 및 개인정보 보호법상 적법 근거와 연결됩니다:

- **서비스 제공**(계약 이행 / 정당한 이익): 페이지 렌더링, 브라우저 내 도구 로직 실행, CDN을 통한 자산 전달.
- **서비스 보안**(정당한 이익): Cloudflare 엣지 보안을 이용한 악용, 서비스 거부 공격, 스크래핑의 탐지 및 완화.
- **서비스 개선**(정당한 이익, 필요한 경우 동의): 어떤 도구가 사용되는지, 이용자가 어디서 막히는지, 어떤 페이지가 느린지를 보여주는 집계 분석.
- **광고 게재**(관할권에 따라 동의 / 정당한 이익): 무료 서비스의 재원 마련을 위한 Google AdSense 광고 게재.
- **문의 응대**(동의 / 정당한 이익): 이메일, 버그 신고, 비즈니스 문의에 대한 회신.
- **법령 준수**(법적 의무): 개인정보 보호법, GDPR, 정보통신망법 등 관련 법령상 의무와 권한 있는 기관의 적법한 요청 이행.` },
				{ title: '제5조 (쿠키의 사용 및 거부 방법)', content: `회사는 소수의 쿠키와 브라우저 저장 기술을 사용합니다:

- **필수 쿠키**: 트래픽 분산과 봇 차단을 위해 엣지 사업자가 설정하는 최소한의 쿠키. 서비스를 이용하려면 비활성화할 수 없습니다.
- **기능성(localStorage)**: 테마·언어 설정. 이 데이터는 기기를 떠나지 않습니다.
- **분석**: 제6조에 기재된 Google Analytics 쿠키.
- **광고**: 제7조에 기재된 Google AdSense/DoubleClick 쿠키.

**이용자는 언제든지 쿠키를 거부할 수 있습니다.** 모든 주요 브라우저에서 쿠키 차단·삭제가 가능합니다: Chrome은 설정 → 개인 정보 보호 및 보안 → 쿠키, Safari는 환경설정 → 개인 정보 보호, Firefox는 설정 → 개인 정보 및 보안, Edge는 설정 → 쿠키 및 사이트 권한. 추적 방지 기능(Safari ITP, Firefox ETP, Brave Shields)도 사용할 수 있습니다. 쿠키를 차단해도 도구는 브라우저에서 정상 작동하며, 다만 일부 환경설정이 방문 간에 유지되지 않을 수 있습니다.` },
				{ title: '제6조 (Google Analytics)', content: `회사는 서비스의 전체적인 이용 현황을 파악하기 위해 Google LLC가 제공하는 Google Analytics 4를 사용합니다. Google Analytics는 방문자를 구분하기 위해 "_ga" 계열 쿠키를 사용하며, 유효기간은 최대 24개월입니다. 회사는 IP 익명화를 설정했고, 도구 입력값이나 이용자가 생성한 텍스트를 Analytics로 전송하지 않으며, 데이터를 집계 형태로만 사용합니다(예: "이번 주 요약기 방문 N회"). Google은 데이터 처리 약정에 따라 회사를 대신하여 이 데이터를 처리합니다. https://tools.google.com/dlpage/gaoptout 의 공식 차단 브라우저 부가기능을 설치하거나 제5조의 방법으로 분석 쿠키를 차단하여 Google Analytics 실행을 방지할 수 있습니다.` },
				{ title: '제7조 (Google AdSense, DoubleClick 쿠키 및 거부)', content: `서비스는 Google AdSense를 통해 게재되는 광고로 운영 재원을 마련합니다.

- 제3자 공급업체인 Google은 DoubleClick(DART) 쿠키를 포함한 쿠키를 사용하여, 이용자의 본 사이트 및 다른 웹사이트 방문 기록을 기반으로 서비스에 광고를 게재합니다.
- 이 쿠키들은 Google과 그 파트너가 맞춤형 광고를 게재하고, 광고 노출 빈도를 제한하며, 광고 성과를 측정할 수 있게 합니다. Google 광고 쿠키의 목록과 유효기간은 Google 광고 개인정보 문서에서 확인할 수 있습니다.
- **거부 방법**: ${ADS_OPTOUT_URL} 의 Google 광고 설정에서 맞춤형 광고를 거부할 수 있습니다. https://www.aboutads.info/choices 에서 다른 여러 제3자 공급업체의 맞춤형 광고도 거부할 수 있습니다.
- 법령상 요구되는 지역(EU, 영국, 한국 등)에서는 맞춤형 광고 쿠키가 설정되기 전에 동의 배너가 표시되며, 해당 배너를 통해 동의를 거부하거나 이후에 철회할 수 있습니다.
- 거부하더라도 광고는 계속 표시되지만, 이용자의 관심사에 맞춰 개인화되지는 않습니다.` },
				{ title: '제8조 (개인정보의 처리위탁 및 국외 이전)', content: `회사는 다음 수탁자에게 필요 최소한의 정보를 위탁하며, 각 수탁자는 기밀 유지와 목적 제한을 요구하는 계약에 따라 행위합니다:

- **Cloudflare, Inc.** — 콘텐츠 전송, DDoS 방어, 엣지 로깅. 데이터: HTTP 요청 메타데이터, 익명화된 IP. 지역: 글로벌 엣지 네트워크.
- **Google LLC (Google Analytics 4)** — 집계 트래픽 분석. 데이터: 익명화된 IP, 페이지뷰, 기기/브라우저 메타데이터.
- **Google LLC (Google AdSense)** — 광고 게재 및 동의 관리. 데이터: 광고 쿠키, 광고 상호작용 이벤트.

회사는 개인정보를 판매·대여·대출하지 않습니다. 일부 수탁자는 전 세계적으로 운영되며 대한민국 또는 유럽경제지역 밖(미국 포함)에서 데이터를 처리할 수 있습니다. 이러한 이전이 발생하는 경우 회사는 유럽위원회가 채택한 표준계약조항(SCC), 해당되는 경우 EU-미국 데이터 프라이버시 프레임워크, 개인정보 보호법상 국외 이전 고지 의무 등의 안전장치에 의존합니다.` },
				{ title: '제9조 (개인정보의 보유 및 이용 기간)', content: `회사는 수집 목적에 필요한 기간 동안만 개인정보를 보유합니다:

- **도구 입력값**: 전혀 보유하지 않음 — 애초에 서버에 도달하지 않습니다.
- **환경설정(localStorage)**: 이용자가 지울 때까지 이용자 브라우저에 보관되며, 회사는 사본을 보유하지 않습니다.
- **분석 데이터**: 집계 형태로 최대 26개월 보유 후 삭제 또는 추가 익명화.
- **엣지 진단 로그**: Cloudflare가 단기간(통상 30일 미만) 순환 보관.
- **이메일 서신**: 후속 문의의 맥락 유지와 한국 상거래 기록 보존 요건 충족을 위해 마지막 교신 후 최대 3년 보관 후 삭제.

한국 법령상 법정 보존 기간이 적용되는 경우(예: 「전자상거래 등에서의 소비자보호에 관한 법률」상 소비자 불만 및 분쟁처리 기록 3년), 해당 기록을 법정 기간 동안만 보존한 후 지체 없이 파기합니다.` },
				{ title: '제10조 (정보주체의 권리)', content: `이용자는 관련 법령에 따라 다음 권리를 가집니다:

- 회사가 보유한 본인 개인정보에 대한 **열람** 및 사본 수령;
- 부정확하거나 불완전한 정보의 **정정**;
- 보유의 우선하는 법적 근거가 없는 경우 정보의 **삭제**("잊힐 권리");
- 정당한 이익에 기반한 처리에 대한 이의 제기를 포함한 **처리 정지·제한**;
- **데이터 이동권** — 제공한 데이터를 구조화된 기계판독 형식으로 수령;
- 언제든지 **동의 철회** (철회 전 처리의 적법성에는 영향 없음);
- 감독기관에 대한 **불만 제기** — 한국은 개인정보보호위원회(privacy.go.kr) 또는 한국인터넷진흥원(KISA, 118), EU는 각국 개인정보 감독기구.

회사는 의도적으로 개인정보를 거의 보유하지 않으므로 대부분의 요청은 즉시 해결됩니다. 도구 입력값과 환경설정은 이용자 본인의 브라우저에만 존재하며, 브라우저의 사이트 데이터를 지우면 완전히 삭제됩니다. 그 밖의 요청(예: 이메일 서신 삭제)은 제11조에 따라 문의해 주세요. 회사는 GDPR(1개월) 및 개인정보 보호법(열람 요구 10일)이 정한 기한 내에 확인된 요청에 무료로 응답합니다. 다만 명백히 근거가 없거나 과도한 요청은 예외입니다.` },
				{ title: '제11조 (개인정보 보호책임자 및 연락처)', content: `회사는 개인정보 관련 문의, 불만 처리, 피해 구제를 담당하는 개인정보 보호책임자를 지정하고 있습니다:

- **개인정보 보호책임자**: ${COMPANY_NAME} 개인정보보호팀
- **이메일**: ${CONTACT_EMAIL} (제목에 "Legal" 또는 "Privacy" 표기)
- **주소**: ${COMPANY_ADDRESS}

개인정보 관련 문의의 수신을 신속히 확인하고 법정 기한 내에 실질적인 답변을 제공합니다. 문의가 적절히 처리되지 않았다고 판단되면 개인정보보호위원회(privacy.go.kr / 국번없이 182), 개인정보침해신고센터(privacy.kisa.or.kr / 국번없이 118), 또는 EU의 경우 해당 지역 감독기구에 문의할 수 있습니다.` },
				{ title: '제12조 (아동의 개인정보)', content: `서비스는 일반 이용자 대상 웹사이트로서 만 14세 미만(한국) 또는 16세 미만(EU) 아동을 대상으로 하지 않습니다. 회사는 아동의 개인정보를 고의로 수집하지 않습니다. 서비스는 계정이 필요 없고 도구 입력값을 저장하지 않으므로 아동의 개인정보를 수집할 위험이 본질적으로 최소화되어 있습니다. 아동이 이메일로 개인정보를 제공했다고 판단되는 경우 ${CONTACT_EMAIL} 로 연락 주시면 지체 없이 삭제하겠습니다.` },
				{ title: '제13조 (개인정보의 안전성 확보 조치)', content: `회사는 취급하는 데이터의 적은 양과 낮은 민감도에 상응하는 관리적·기술적·물리적 조치를 취합니다. 모든 트래픽은 TLS로 암호화되고, 침해될 수 있는 이용자 콘텐츠의 서버측 데이터베이스가 존재하지 않으며, 분석 데이터와 서신에 대한 내부 접근은 필요 최소한의 권한 있는 인원으로 제한되고, 인프라 제공업체(Cloudflare, Google)는 ISO 27001, SOC 2 등 업계 표준 인증을 유지합니다. 인터넷 전송 방식 중 100% 안전한 것은 없지만, 당사의 아키텍처는 애초에 존재하는 데이터를 최소화함으로써 위험을 최소화합니다.` },
				{ title: '제14조 (개인정보 처리방침의 변경)', content: `회사는 법령, 기술, 처리 관행의 변화를 반영하여 본 방침을 갱신할 수 있습니다. 중요한 변경이 있는 경우 시행 최소 7일 전(이용자 권리에 중대한 영향을 미치는 변경은 30일 전)에 본 페이지에 갱신된 방침을 게시하고 상단의 "최종 수정일"을 업데이트합니다. 갱신된 방침 시행일 이후 서비스를 계속 이용하는 것은 변경 사항을 인지했음을 의미합니다. 이전 버전은 ${CONTACT_EMAIL} 로 요청하시면 제공됩니다.

본 방침은 ${EFFECTIVE_DATE}부터 시행되며, ${LAST_UPDATED}에 최종 수정되었습니다.` }
			]
		},

		ja: {
			title: 'プライバシーポリシー',
			lastUpdated: `最終更新日: ${LAST_UPDATED}`,
			effective: `施行日: ${EFFECTIVE_DATE}`,
			intro: `${SITE_NAME}（以下「本サービス」）を運営する ${COMPANY_NAME}（以下「当社」）は、ユーザーのプライバシーを尊重し、大韓民国「個人情報保護法」（PIPA）、EU「一般データ保護規則」（GDPR）を含む適用法令に従い、個人データを適法・公正・透明に取り扱うことをお約束します。本プライバシーポリシーは、当社が収集する情報、その利用方法、共有する第三者、適用法の下でのユーザーの権利、およびその行使方法を定めるものです。${SITE_NAME} にアクセスまたはこれを利用することにより、ユーザーは本ポリシーを読み、理解したことを確認したものとみなされます。`,
			sections: [
				{ title: '第1条（適用範囲）', content: `本ポリシーは、https://${SITE_DOMAIN} でホストされるウェブサイト、すべてのサブドメイン、および当社が運営する関連サービス（以下総称して「本サービス」）に適用されます。本サービスからリンクされる、または本サービス上の広告に表示される第三者のウェブサイト、AI アシスタント、広告主には適用されません。特に、当社ツールが生成したプロンプトをコピーして第三者の AI サービス（ChatGPT、Claude、Gemini 等）に貼り付ける場合、そのサービスの利用には当該事業者自身のプライバシーポリシーのみが適用されます。第三者に個人データを提供する前に、その事業者のプライバシー通知をご確認ください。` },
				{ title: '第2条（収集する個人情報）', content: `当社は、${SITE_NAME} を可能な限り少ない個人データしか収集しないよう意図的に設計しています。具体的には:

- **アカウント情報**: ${SITE_NAME} にアカウントは不要です。登録フロー、メールアドレスの収集、パスワードは存在せず、当社はユーザーに関するアカウント記録を一切保有しません。
- **ツールへの入力**: ツールに入力したテキストやコードはブラウザ内で処理されます（第3条参照）。入力内容を当社サーバーへ送信・記録・保存することはありません。
- **設定**: テーマ・言語の選択はブラウザの localStorage にのみ保存され、当社のインフラに到達しません。
- **分析データ（自動収集）**: ページビュー、参照 URL、おおよその国（短縮された IP アドレスから導出）、ブラウザ種別、OS、画面サイズ、言語設定などの集計・仮名化された指標。
- **広告データ**: 第7条に記載する Google AdSense が設定する Cookie 及び類似の識別子。
- **診断ログ**: エッジ事業者である Cloudflare が、セキュリティ、不正利用防止、容量計画のため、HTTP リクエストのメタデータ（時刻、メソッド、パス、応答ステータス、エッジ拠点、匿名化 IP）を短期間自動記録します。
- **コミュニケーションデータ**: メールでお問い合わせいただく場合、メールアドレス、メッセージ内容、添付ファイルを受領します。

当社は、要配慮個人情報（健康、宗教、生体情報等）、政府発行の識別子、決済カード番号、精密な位置情報を故意に収集することはありません。` },
				{ title: '第3条（AI ツールに入力されたテキストの取り扱い）', content: `ユーザーから最も多く寄せられる質問 — 「ツールに入力したテキストはどうなるのか」 — に答える条項です。

- **処理はユーザーの端末上で行われます。** 当社のツール（AI 翻訳、テキスト要約、プロンプト生成、画像プロンプトビルダー、コード解説、メール作成、ハッシュタグ生成、ライティングアシスタント）は、そのロジックをブラウザ内で実行します。入力されたテキストは、出力を生成するために端末のメモリ上で一時的に使用され、入力を消去するかページを離れると破棄されます。
- **当社はテキストを保存しません。** いかなるツール入力も、当社サーバーに送信・記録されず、恒久的に保存されることもありません。ユーザーテキストのサーバー側データベースは存在しません。
- **テキストを学習に使用しません。** ユーザーの入力が、当社によって、または当社のために、機械学習モデルの学習・ファインチューニング・評価に使用されることはありません。
- **第三者 AI サービスの利用はユーザーの選択です。** ツールが外部 AI アシスタント向けのプロンプトを生成する場合、そのプロンプトはユーザー自身がコピーして貼り付けたときに初めて端末を離れます。その時点以降のテキストの処理 — AI モデル API への送信や保持を含む — は、本ポリシーではなく、当該第三者事業者の規約とプライバシーポリシーに従います。将来、ユーザーのテキストを AI モデル API に直接送信するツールを導入する場合には、送信前にツールページ上で明確にその旨を表示し、結果生成の目的に限り暗号化された接続でテキストを送信し、恒久的な保存は行いません。` },
				{ title: '第4条（利用目的と法的根拠）', content: `当社は、収集した限られた情報を以下の目的で利用します。各目的は GDPR 上の法的根拠および PIPA 上の適法根拠に紐づいています:

- **本サービスの提供**（契約の履行 / 正当な利益）: ページのレンダリング、ブラウザ内でのツールロジックの実行、CDN によるアセット配信。
- **本サービスの保護**（正当な利益）: Cloudflare のエッジセキュリティによる不正利用、DoS 攻撃、スクレイピングの検知と緩和。
- **本サービスの改善**（正当な利益、必要な場合は同意）: どのツールが使われ、ユーザーがどこでつまずき、どのページが遅いかを示す集計分析。
- **広告の表示**（法域により同意 / 正当な利益）: 無料サービスの資金源として Google AdSense を通じた広告配信。
- **お問い合わせへの対応**（同意 / 正当な利益）: メール、不具合報告、ビジネスに関する問い合わせへの返信。
- **法令遵守**（法的義務）: PIPA、GDPR、韓国の通信・ネットワーク関連法の要件、および権限ある当局からの適法な要請への対応。` },
				{ title: '第5条（Cookie と拒否方法）', content: `当社は少数の Cookie とブラウザストレージ技術を使用します:

- **厳密に必要な Cookie**: トラフィック分散とボット対策のためにエッジ事業者が設定する最小限の Cookie。本サービスを利用する場合、無効化できません。
- **機能性（localStorage）**: テーマ・言語設定。このデータは端末を離れません。
- **分析**: 第6条に記載する Google Analytics の Cookie。
- **広告**: 第7条に記載する Google AdSense/DoubleClick の Cookie。

**ユーザーはいつでも Cookie を拒否できます。** 主要なブラウザはすべて Cookie のブロック・削除に対応しています: Chrome は設定 → プライバシーとセキュリティ → Cookie、Safari は環境設定 → プライバシー、Firefox は設定 → プライバシーとセキュリティ、Edge は設定 → Cookie とサイトのアクセス許可。トラッキング防止機能（Safari ITP、Firefox ETP、Brave Shields）も利用できます。Cookie をブロックしてもツールはブラウザ内で問題なく動作しますが、一部の設定が訪問間で保持されない場合があります。` },
				{ title: '第6条（Google Analytics）', content: `当社は、本サービスの全体的な利用状況を把握するため、Google LLC が提供する Google Analytics 4 を使用しています。Google Analytics は訪問者を区別するために「_ga」系の Cookie を使用し、有効期間は最長 24 か月です。当社は IP 匿名化を設定しており、ツールへの入力やユーザーが生成したテキストを Analytics に送信せず、データを集計形態でのみ使用します（例:「今週の要約ツールの訪問数は N 回」）。Google はデータ処理条項に基づき当社に代わってこのデータを処理します。https://tools.google.com/dlpage/gaoptout の公式オプトアウトアドオンをインストールするか、第5条の方法で分析 Cookie をブロックすることで、Google Analytics の実行を防げます。` },
				{ title: '第7条（Google AdSense、DoubleClick Cookie とオプトアウト）', content: `本サービスは Google AdSense を通じて配信される広告によって運営されています。

- 第三者ベンダーである Google は、DoubleClick（DART）Cookie を含む Cookie を使用し、ユーザーの本サイトおよび他のウェブサイトへの訪問に基づいて本サービス上に広告を配信します。
- これらの Cookie により、Google とそのパートナーはパーソナライズ広告の配信、広告表示頻度の制限、広告効果の測定を行うことができます。Google の広告 Cookie の一覧と有効期間は、Google の広告プライバシー文書で確認できます。
- **オプトアウト**: ${ADS_OPTOUT_URL} の Google 広告設定でパーソナライズ広告をオプトアウトできます。さらに https://www.aboutads.info/choices で、他の多くの第三者ベンダーのパーソナライズ広告もオプトアウトできます。
- 法令上必要とされる地域（EU、英国、韓国等）では、パーソナライズ広告 Cookie が設定される前に同意バナーが表示され、そのバナーから同意を拒否または後から撤回できます。
- オプトアウトしても広告は表示されますが、ユーザーの興味関心に基づくパーソナライズは行われません。` },
				{ title: '第8条（第三者への処理委託と国外移転）', content: `当社は、機密保持と目的制限を義務付ける契約の下で、以下の処理者に必要最小限の情報を委託しています:

- **Cloudflare, Inc.** — コンテンツ配信、DDoS 対策、エッジロギング。データ: HTTP リクエストメタデータ、匿名化 IP。地域: グローバルエッジネットワーク。
- **Google LLC（Google Analytics 4）** — 集計トラフィック分析。データ: 匿名化 IP、ページビュー、デバイス/ブラウザメタデータ。
- **Google LLC（Google AdSense）** — 広告配信と同意管理。データ: 広告 Cookie、広告インタラクションイベント。

当社は個人データを販売・貸与しません。一部の処理者はグローバルに事業を展開しており、大韓民国または欧州経済領域の外（米国を含む）でデータを処理する場合があります。かかる移転が生じる場合、当社は欧州委員会が採択した標準契約条項（SCC）、該当する場合は EU-米国データプライバシーフレームワーク、および PIPA の国外移転に関する開示義務などのセーフガードに依拠します。` },
				{ title: '第9条（個人情報の保有期間）', content: `当社は、収集目的に必要な期間に限り個人データを保有します:

- **ツールへの入力**: 一切保有しません — そもそもサーバーに到達しません。
- **設定（localStorage）**: ユーザーが消去するまでユーザーのブラウザに保持され、当社は複製を保有しません。
- **分析データ**: 集計形態で最長 26 か月保有し、その後削除またはさらに匿名化します。
- **エッジ診断ログ**: Cloudflare が短期間（通常 30 日未満）のローリングウィンドウで保持します。
- **メールのやり取り**: フォローアップの文脈維持と韓国の商業記録保存要件のため、最後のやり取りから最長 3 年間保持した後、削除します。

韓国法上の法定保存期間が適用される場合（例: 電子商取引消費者保護法に基づく消費者苦情・紛争処理記録は 3 年）、当該記録を法定期間に限り保存し、その後遅滞なく破棄します。` },
				{ title: '第10条（ユーザーの権利）', content: `適用法に従い、ユーザーは以下の権利を有します:

- 当社が保有する自己の個人データへの**アクセス**と写しの受領;
- 不正確または不完全なデータの**訂正**;
- 保有を上回る法的根拠がない場合のデータの**消去**（「忘れられる権利」）;
- 正当な利益に基づく処理への異議を含む、処理の**制限・異議申立て**;
- **データポータビリティ** — 提供したデータを構造化された機械可読形式で受領;
- いつでも**同意を撤回**する権利（撤回前の処理の適法性には影響しません）;
- 監督機関への**苦情申立て** — 韓国では個人情報保護委員会（privacy.go.kr）または韓国インターネット振興院（KISA、118）、EU では各国のデータ保護機関。

当社は意図的にほとんど個人データを保有しないため、大半の請求は即座に満たされます。ツールへの入力と設定はユーザー自身のブラウザにのみ存在し、ブラウザのサイトデータを消去すれば完全に削除されます。それ以外の請求（例: メールのやり取りの削除）は第11条の方法でご連絡ください。当社は、確認済みの請求に対し、GDPR（1 か月）および PIPA（閲覧請求は 10 日）が定める期限内に、原則無料で対応します。ただし、明らかに根拠のない請求や過剰な請求は除きます。` },
				{ title: '第11条（個人情報保護責任者と連絡先）', content: `当社は、個人データに関する問い合わせ、苦情処理、救済を担当する個人情報保護責任者を指定しています:

- **個人情報保護責任者**: ${COMPANY_NAME} プライバシーチーム
- **メール**: ${CONTACT_EMAIL}（件名に「Legal」または「Privacy」と記載）
- **住所**: ${COMPANY_ADDRESS}

プライバシーに関するお問い合わせは速やかに受領確認を行い、法定期限内に実質的な回答を提供します。お問い合わせが適切に処理されなかったとお考えの場合は、韓国個人情報保護委員会（privacy.go.kr）、または EU の場合はお住まいの地域の監督機関にご連絡いただけます。` },
				{ title: '第12条（子どものプライバシー）', content: `本サービスは一般向けウェブサイトであり、14 歳未満（韓国）または 16 歳未満（EU）の子どもを対象としていません。当社が子どもの個人データを故意に収集することはありません。本サービスはアカウントを必要とせず、ツールへの入力も保存しないため、子どもの個人データを収集するリスクは本質的に最小限です。子どもがメールで個人データを提供したと思われる場合は、${CONTACT_EMAIL} までご連絡ください。速やかに削除します。` },
				{ title: '第13条（安全管理措置）', content: `当社は、取り扱うデータの量の少なさと機密性の低さに見合った管理的・技術的・物理的措置を講じています。すべてのトラフィックは TLS で暗号化され、侵害され得るユーザーコンテンツのサーバー側データベースは存在せず、分析データとメールへの内部アクセスは必要最小限の権限を持つ担当者に限定され、インフラ提供者（Cloudflare、Google）は ISO 27001、SOC 2 などの業界標準認証を維持しています。インターネット上の伝送方式に 100% 安全なものはありませんが、当社のアーキテクチャは、そもそも存在するデータを最小化することでリスクを最小化しています。` },
				{ title: '第14条（本ポリシーの変更）', content: `当社は、法令、技術、または取り扱い実務の変化を反映するため、本ポリシーを更新することがあります。重要な変更を行う場合は、施行の少なくとも 7 日前（ユーザーの権利に重大な影響を及ぼす変更は 30 日前）に更新後のポリシーを本ページに掲示し、冒頭の「最終更新日」を更新します。更新後のポリシーの施行日以降に本サービスの利用を継続することは、変更を認識したものとみなされます。過去のバージョンは ${CONTACT_EMAIL} へのご請求により提供します。

本ポリシーは ${EFFECTIVE_DATE} から施行され、${LAST_UPDATED} に最終更新されました。` }
			]
		},

		zh: {
			title: '隐私政策',
			lastUpdated: `最后更新：${LAST_UPDATED}`,
			effective: `生效日期：${EFFECTIVE_DATE}`,
			intro: `${SITE_NAME}（以下称"本服务"）的运营者 ${COMPANY_NAME}（以下称"公司"或"我们"）尊重您的隐私，并承诺依照适用法律 —— 包括大韩民国《个人信息保护法》（PIPA）和欧盟《通用数据保护条例》（GDPR）—— 合法、公正、透明地处理个人数据。本隐私政策说明我们收集哪些信息、如何使用、与哪些第三方共享、您在适用法律下享有的权利以及如何行使这些权利。访问或使用 ${SITE_NAME}，即表示您确认已阅读并理解本政策。`,
			sections: [
				{ title: '1. 适用范围', content: `本政策适用于托管在 https://${SITE_DOMAIN} 的网站、所有子域名以及我们运营的相关服务（统称"本服务"）。本政策不适用于我们链接到的、或可能出现在本服务广告中的第三方网站、AI 助手或广告主。特别地，当您复制我们工具生成的提示词并粘贴到第三方 AI 服务（如 ChatGPT、Claude、Gemini）时，您对该服务的使用仅受该提供商自己的隐私政策约束。在向第三方提供个人数据之前，请先查阅其隐私声明。` },
				{ title: '2. 我们收集的个人信息', content: `我们有意将 ${SITE_NAME} 设计为尽可能少地收集个人数据。具体而言:

- **账号数据**: ${SITE_NAME} 不需要账号。没有注册流程、不收集邮箱、没有密码，因此我们不持有任何关于您的账号记录。
- **工具输入**: 您在工具中输入的文本、代码或其他内容在您的浏览器中处理（见第 3 条）。我们不会将输入内容传输到、记录在或存储于我们的服务器。
- **偏好设置**: 主题和语言选择仅保存在您浏览器的 localStorage 中，从不到达我们的基础设施。
- **分析数据（自动收集）**: 页面访问量、来源 URL、大致国家（由截断的 IP 地址推得）、浏览器类型、操作系统、屏幕尺寸、语言偏好等聚合化、假名化指标。
- **广告数据**: 第 7 条所述由 Google AdSense 设置的 Cookie 及类似标识符。
- **诊断日志**: 我们的边缘服务商 Cloudflare 出于安全、防滥用和容量规划目的，自动记录 HTTP 请求元数据（时间戳、方法、路径、响应状态、边缘节点、匿名化 IP），保留期很短。
- **通信数据**: 您通过电子邮件联系我们时，我们会收到您的邮箱地址、消息内容及您选择发送的附件。

我们不会有意收集特殊类别的个人数据（如健康、宗教、生物特征）、政府颁发的身份识别号、支付卡号或精确地理位置。` },
				{ title: '3. 您提交给 AI 工具的文本如何被处理', content: `本条回答用户最常问的问题：我输入到工具里的文本会怎样？

- **处理在您的设备上进行。** 我们的工具（AI 翻译器、文本摘要、提示词生成器、图像提示词构建器、代码解释器、邮件写作器、标签生成器、写作助手）的逻辑都在您的浏览器中运行。您输入的文本仅在设备内存中被临时用于生成输出，当您清除输入或离开页面时即被丢弃。
- **我们不存储您的文本。** 任何工具输入都不会被传输到我们的服务器、被记录或被永久存储。不存在任何用户文本的服务器端数据库。
- **我们不用您的文本训练模型。** 您的输入绝不会被我们或代表我们的任何一方用于训练、微调或评估任何机器学习模型。
- **第三方 AI 服务由您自主选择。** 当工具生成供外部 AI 助手使用的提示词时，只有当您自己复制并粘贴它时，该提示词才会离开您的设备。自那一刻起，文本的处理 —— 包括向 AI 模型 API 的传输和任何保留 —— 受第三方提供商的条款和隐私政策约束，而非本政策。如果我们将来推出直接将您的文本发送到 AI 模型 API 的工具，我们会在您提交任何内容之前在工具页面上明确说明，仅为生成结果而通过加密连接传输文本，并且不会永久存储。` },
				{ title: '4. 使用目的与法律依据', content: `我们将收集到的有限信息用于以下目的，每项目的均对应 GDPR 下的法律依据和 PIPA 下的合法根据:

- **提供本服务**（履行合同 / 正当利益）: 渲染页面、在您的浏览器中执行工具逻辑、通过 CDN 交付资源。
- **保护本服务**（正当利益）: 利用 Cloudflare 边缘安全检测并缓解滥用、拒绝服务攻击和抓取行为。
- **改进本服务**（正当利益，必要时经同意）: 聚合分析，帮助我们了解哪些工具被使用、用户在哪里遇到困难、哪些页面缓慢。
- **展示广告**（视司法辖区而定，基于同意 / 正当利益）: 通过 Google AdSense 投放广告，为免费服务提供资金。
- **回复您**（同意 / 正当利益）: 回复邮件、错误报告和商务咨询。
- **法律合规**（法律义务）: 满足 PIPA、GDPR、韩国电信与网络相关法律的要求，以及主管机关的合法请求。` },
				{ title: '5. Cookie 及拒绝方式', content: `我们使用少量 Cookie 和浏览器存储技术:

- **严格必要**: 边缘服务商为均衡流量、防御机器人而设置的最小限度 Cookie。若要使用本服务则无法禁用。
- **功能性（localStorage）**: 主题和语言偏好。这些数据从不离开您的设备。
- **分析**: 第 6 条所述的 Google Analytics Cookie。
- **广告**: 第 7 条所述的 Google AdSense/DoubleClick Cookie。

**您可以随时拒绝 Cookie。** 所有主流浏览器都支持阻止或删除 Cookie: Chrome 在"设置 → 隐私和安全 → Cookie"；Safari 在"偏好设置 → 隐私"；Firefox 在"设置 → 隐私与安全"；Edge 在"设置 → Cookie 和网站权限"。您也可以启用跟踪保护（Safari ITP、Firefox ETP、Brave Shields）。阻止 Cookie 不会影响工具的运行 —— 它们本来就在您的浏览器中运行 —— 只是某些偏好设置可能无法在访问之间保留。` },
				{ title: '6. Google Analytics', content: `我们使用 Google LLC 提供的 Google Analytics 4 来了解本服务的整体使用情况。Google Analytics 使用"_ga"系列 Cookie 来区分访问者，有效期最长 24 个月。我们已配置 IP 匿名化，不会将工具输入或任何用户生成的文本发送给 Analytics，并且仅以聚合形式使用数据（例如"摘要工具本周有 N 次访问"）。Google 根据其数据处理条款代表我们处理这些数据。您可以安装官方退出浏览器插件（https://tools.google.com/dlpage/gaoptout），或按第 5 条所述阻止分析 Cookie，从而阻止 Google Analytics 运行。` },
				{ title: '7. Google AdSense、DoubleClick Cookie 与退出方式', content: `本服务由通过 Google AdSense 投放的广告提供资金。

- 作为第三方供应商，Google 使用 Cookie —— 包括 DoubleClick（DART）Cookie —— 基于您对本站及其他网站的访问在本服务上投放广告。
- 这些 Cookie 使 Google 及其合作伙伴能够投放个性化广告、限制广告展示频率并衡量广告效果。Google 广告 Cookie 的列表及其有效期可在 Google 的广告隐私文档中查阅。
- **退出方式**: 您可以访问 Google 广告设置（${ADS_OPTOUT_URL}）退出个性化广告，还可以在 https://www.aboutads.info/choices 退出许多其他第三方供应商的个性化广告。
- 在法律要求的地区（欧盟、英国、韩国等），在设置任何个性化广告 Cookie 之前会显示同意横幅，您可以通过该横幅拒绝或事后撤回同意。
- 退出后您仍会看到广告，但广告将不再基于您的兴趣进行个性化。` },
				{ title: '8. 第三方处理者与跨境传输', content: `我们仅与以下处理者共享必要的最少信息，各处理者均依据要求保密和目的限制的协议行事:

- **Cloudflare, Inc.** — 内容分发、DDoS 防护、边缘日志。数据: HTTP 请求元数据、匿名化 IP。区域: 全球边缘网络。
- **Google LLC（Google Analytics 4）** — 聚合流量分析。数据: 匿名化 IP、页面访问量、设备/浏览器元数据。
- **Google LLC（Google AdSense）** — 广告投放与同意管理。数据: 广告 Cookie、广告交互事件。

我们不出售、出租或出借您的个人数据。部分处理者在全球运营，可能在大韩民国或欧洲经济区之外（包括美国）处理数据。发生此类传输时，我们依赖的保障措施包括欧盟委员会通过的标准合同条款（SCC）、适用时的欧美数据隐私框架，以及 PIPA 关于跨境传输的披露义务。` },
				{ title: '9. 个人信息的保留期限', content: `我们仅在实现收集目的所必需的期间内保留个人数据:

- **工具输入**: 完全不保留 —— 它们从不到达我们的服务器。
- **偏好设置（localStorage）**: 保留在您的浏览器中直至您清除；我们从不持有副本。
- **分析数据**: 以聚合形式最长保留 26 个月，之后删除或进一步匿名化。
- **边缘诊断日志**: 由 Cloudflare 以短期滚动窗口保留（通常少于 30 天）。
- **电子邮件往来**: 为保持后续咨询的上下文并满足韩国商业记录保存要求，自最后一次往来起最长保留 3 年，之后删除。

当韩国法律规定了法定保存期限时（例如《电子商务消费者保护法》规定的消费者投诉及纠纷处理记录为 3 年），我们仅在法定期限内保留相关记录，期满后立即销毁。` },
				{ title: '10. 您的权利', content: `在适用法律允许的范围内，您有权:

- **查阅**我们持有的关于您的个人数据并获取副本;
- **更正**不准确或不完整的数据;
- 在不存在优先的法律保留依据时**删除**您的数据（"被遗忘权"）;
- **限制或反对**处理，包括反对基于正当利益的处理;
- **数据可携权** —— 以结构化、机器可读的格式接收您提供的数据;
- 随时**撤回同意**，且不影响撤回前处理的合法性;
- 向监管机构**投诉** —— 在韩国为个人信息保护委员会（privacy.go.kr）或韩国互联网振兴院（KISA，118）；在欧盟为您所在国的数据保护机构。

由于我们有意几乎不持有任何个人数据，大多数请求可以立即得到满足: 工具输入和偏好设置只存在于您自己的浏览器中，清除浏览器的站点数据即可将其完全删除。其他事项（如删除邮件往来）请按第 11 条与我们联系。对经核实的请求，我们将在 GDPR（一个月）和 PIPA（查阅请求为 10 天）规定的期限内免费回应，除非请求明显无理或过度。` },
				{ title: '11. 个人信息保护负责人及联系方式', content: `公司已指定负责处理个人数据咨询、投诉和救济的个人信息保护负责人:

- **个人信息保护负责人**: ${COMPANY_NAME} 隐私团队
- **电子邮件**: ${CONTACT_EMAIL}（请在主题中注明 "Legal" 或 "Privacy"）
- **地址**: ${COMPANY_ADDRESS_EN}

我们会及时确认收到隐私咨询，并在法定期限内提供实质性答复。如果您认为您的咨询未得到妥善处理，可以联系韩国个人信息保护委员会（privacy.go.kr），或在欧盟联系您当地的监管机构。` },
				{ title: '12. 儿童隐私', content: `本服务是面向一般公众的网站，不以未满 14 周岁（韩国）或未满 16 周岁（欧盟）的儿童为对象。我们不会有意收集儿童的个人数据。由于本服务无需账号且不存储工具输入，收集儿童个人数据的风险在本质上被降到了最低。如果您认为某个儿童通过电子邮件向我们提供了个人数据，请联系 ${CONTACT_EMAIL}，我们将及时删除。` },
				{ title: '13. 安全措施', content: `我们采取与所处理数据的低数量、低敏感度相称的管理、技术和物理措施: 所有流量均以 TLS 加密；不存在可能被入侵的用户内容服务器端数据库；对分析数据和通信的内部访问仅限于有必要知悉的授权人员；我们的基础设施提供商（Cloudflare、Google）持有 ISO 27001、SOC 2 等行业标准认证。互联网上没有任何传输方式是 100% 安全的，但我们的架构通过从源头上最小化存在的数据来最小化风险。` },
				{ title: '14. 本政策的变更', content: `我们可能更新本政策以反映法律、技术或处理实践的变化。发生重大变更时，我们将至少在生效前七（7）天（对您的权利有重大影响的变更为三十（30）天）在本页面发布更新后的政策，并更新顶部的"最后更新"日期。在更新政策生效日之后继续使用本服务即表示您已知悉变更。历史版本可发邮件至 ${CONTACT_EMAIL} 索取。

本政策自 ${EFFECTIVE_DATE} 起生效，最后更新于 ${LAST_UPDATED}。` }
			]
		}
	};

	$: t = content[lang] || content.en;
</script>

<svelte:head>
	<title>{t.title} - {SITE_NAME}</title>
	<meta name="description" content={t.intro.slice(0, 160)} />
</svelte:head>

<div class="max-w-4xl mx-auto px-4 py-12">
	<h1 class="text-3xl font-bold text-gray-900 dark:text-dark-100 mb-2">{t.title}</h1>
	<p class="text-gray-500 dark:text-dark-500 text-sm">{t.lastUpdated}</p>
	<p class="text-gray-500 dark:text-dark-500 text-sm mb-8">{t.effective}</p>

	<p class="text-gray-700 dark:text-dark-300 mb-8 leading-relaxed">{t.intro}</p>

	<div class="space-y-8">
		{#each t.sections as section}
			<section>
				<h2 class="text-xl font-semibold text-gray-900 dark:text-dark-100 mb-3">{section.title}</h2>
				<div class="text-gray-700 dark:text-dark-300 leading-relaxed whitespace-pre-line">
					{@html section.content.replace(/\*\*([^*]+)\*\*/g, '<strong class="text-gray-900 dark:text-dark-100">$1</strong>')}
				</div>
			</section>
		{/each}
	</div>

	<div class="mt-12 pt-8 border-t border-gray-200 dark:border-dark-700">
		<a href="/{lang}" class="text-primary-500 hover:text-primary-400 transition-colors">
			← {lang === 'ko' ? '홈으로 돌아가기' : lang === 'ja' ? 'ホームに戻る' : lang === 'zh' ? '返回首页' : 'Back to Home'}
		</a>
	</div>
</div>
