<script lang="ts">
	import { page } from '$app/stores';
	import type { Locale } from '$lib/i18n';

	$: lang = ($page.params.lang || 'en') as Locale;

	const SITE_NAME = 'SDK.ac';
	const SITE_DOMAIN = 'sdk.ac';
	const CONTACT_EMAIL = 'contact@sdk.ac';
	const COMPANY_NAME = 'SDK Co., Ltd.';
	const BUSINESS_NUMBER = '871-81-03242';
	const ECOMMERCE_NUMBER = '2024-고양일산서-1820';
	const COMPANY_ADDRESS = '제주특별자치도 제주시 남성로 127, 4층';
	const COMPANY_ADDRESS_EN = '4F, 127 Namseong-ro, Jeju-si, Jeju Special Self-Governing Province, Republic of Korea';
	const EFFECTIVE_DATE = '2025-01-15';
	const LAST_UPDATED = '2026-07-02';

	type TermsContent = {
		title: string;
		lastUpdated: string;
		effective: string;
		intro: string;
		sections: { title: string; content: string }[];
	};

	const content: Partial<Record<Locale, TermsContent>> & { en: TermsContent } = {
		en: {
			title: 'Terms of Service',
			lastUpdated: `Last Updated: ${LAST_UPDATED}`,
			effective: `Effective Date: ${EFFECTIVE_DATE}`,
			intro: `These Terms of Service (the "Terms") form a legally binding agreement between you (the "User", "you") and ${COMPANY_NAME} (the "Company", "we", "our", "us"), the operator of ${SITE_NAME}, accessible at https://${SITE_DOMAIN} (the "Service"). By accessing or using the Service, you confirm that you have read, understood, and agree to be bound by these Terms and by our Privacy Policy. If you do not agree to these Terms, please discontinue use of the Service.`,
			sections: [
				{ title: 'Article 1 (Purpose)', content: `The purpose of these Terms is to define the rights, obligations, responsibilities, and other necessary matters between the Company and the User in connection with the use of ${SITE_NAME}, a collection of free, browser-based AI utility tools provided by the Company. Any matter not stipulated in these Terms shall be governed by the relevant laws of the Republic of Korea — including the Act on the Consumer Protection in Electronic Commerce, the Act on Promotion of Information and Communications Network Utilisation and Information Protection, and the Personal Information Protection Act — by generally accepted industry practice, and by applicable international law.` },
				{ title: 'Article 2 (Definitions)', content: `For the purposes of these Terms, the following definitions apply:

- **"Company"** means ${COMPANY_NAME}, a corporation established under the laws of the Republic of Korea, with business registration number ${BUSINESS_NUMBER} and e-commerce sales registration number ${ECOMMERCE_NUMBER}, located at ${COMPANY_ADDRESS_EN}.
- **"Service"** means the website hosted at https://${SITE_DOMAIN}, all subdomains, and all tools, content, guides, and related materials made available by the Company thereon.
- **"User"** means any individual or entity that accesses or uses the Service. The Service requires no registration; every visitor is a User.
- **"Tools"** means the AI-assisted utilities provided through the Service, currently including the AI translator, text summarizer, prompt generator, image prompt builder, code explainer, email writer, hashtag generator, and writing assistant, and any tools added later.
- **"User Input"** means any text, code, or other material a User enters into a Tool. User Input is processed in the User's browser and is not transmitted to or stored on the Company's servers.
- **"AI Output"** means any prompt, text, or other result produced by a Tool from User Input, as well as any content subsequently generated by a third-party AI service from a prompt created with a Tool.` },
				{ title: 'Article 3 (Posting and Amendment of the Terms)', content: `(1) The Company shall post these Terms on the Service so that Users can readily review them at any time.

(2) The Company may amend these Terms to the extent that the amendment does not violate applicable law. When the Company amends the Terms, it shall post the amended Terms on the Service, together with the effective date and the reasons for the amendment, no less than seven (7) days before the effective date. Where the amendment is disadvantageous or material to Users, the Company shall post the notice at least thirty (30) days before the effective date.

(3) A User who does not agree to an amendment may discontinue use of the Service before the effective date. A User who continues to use the Service on or after the effective date shall be deemed to have accepted the amended Terms.` },
				{ title: 'Article 4 (Provision of the Service)', content: `(1) The Company provides the Service free of charge, funded by advertising, on an "as available" basis. The Service includes, without limitation:

- Eight AI-assisted Tools: an AI translator, a text summarizer, a prompt generator, an image prompt builder, a code explainer, an email writer, a hashtag generator, and a writing assistant;
- Practical guides and reference articles on using AI models effectively;
- Multilingual support across nine interface languages.

(2) The Tools execute their logic in the User's browser. Where a Tool produces a prompt intended for an external AI assistant (such as ChatGPT, Claude, or Gemini), the User's use of that external service is governed by that provider's own terms, not by these Terms.

(3) The Service is in principle available 24 hours a day, 365 days a year, except during scheduled maintenance, emergency repairs, telecommunications or infrastructure-provider outages, force-majeure events, or other circumstances beyond the Company's reasonable control.` },
				{ title: 'Article 5 (Use of the Service)', content: `(1) The User may use the Service anonymously and without registration, for lawful personal or internal-business purposes, in accordance with these Terms and applicable law.

(2) Use of the Service commences when the User accesses the Service; no separate application or approval procedure applies.

(3) The User acknowledges that User Input is processed entirely on the User's own device and does not reach the Company's servers, and that the Company therefore cannot recover, restore, or delete User Input on the User's behalf.

(4) The User shall comply with any operational policies, usage notices, and precautions that the Company posts on the Service, including the notes on AI limitations displayed on each Tool page.` },
				{ title: 'Article 6 (User Obligations)', content: `The User shall:

(1) Comply with applicable laws, these Terms, and any usage guidance posted on the Service;
(2) Independently verify the accuracy, legality, and suitability of any AI Output before relying on it or publishing it, as further described in Article 10;
(3) Ensure that the User holds all rights necessary to any text, code, or other material the User enters into a Tool, and that such entry does not infringe the rights of any third party or breach any duty of confidentiality;
(4) Not misrepresent AI Output as independently verified fact, professional advice, or the work of a human expert where such representation could mislead others;
(5) Bear sole responsibility for the consequences of the User's use of the Service and of any AI Output, including its publication, distribution, or commercial use;
(6) Not interfere with the operation of the Service or damage the reputation of the Company or of other Users.` },
				{ title: 'Article 7 (Prohibited Activities)', content: `The User shall not engage in any of the following:

(1) Using the Tools to create, refine, or optimise content that is illegal, fraudulent, defamatory, harassing, hateful, discriminatory, sexually exploitative, or that promotes violence or self-harm;
(2) Using the Tools to produce deceptive content, including phishing messages, scam emails, disinformation intended to mislead the public, or impersonation of any person or organisation;
(3) Using the Tools to facilitate infringement of copyright, trademark, trade-secret, privacy, or publicity rights of any third party;
(4) Accessing or attempting to access the Service by abnormal means, including automated scraping, bulk crawling that exceeds what robots.txt permits, or circumvention of technical protections;
(5) Transmitting or distributing viruses, malware, or any code designed to disrupt or damage the Service or third-party systems;
(6) Interfering with advertising, analytics, security features, or other technical components of the Service, or artificially generating ad impressions or clicks;
(7) Imposing an unreasonable load on the Service infrastructure or materially degrading the experience of other Users;
(8) Reselling, sublicensing, or misrepresenting the Service itself as the User's own product or service;
(9) Any other act that violates applicable law, public order, or good morals.

If the Company reasonably determines that a User has engaged in a prohibited activity, the Company may, with or without prior notice, restrict or block the User's access (for example by rate-limiting or IP blocking) and, where required, refer the matter to law-enforcement authorities. A User subject to such a measure may object in writing to ${CONTACT_EMAIL}, and the Company shall review the objection in good faith within fourteen (14) days.` },
				{ title: 'Article 8 (Modification, Suspension, and Discontinuation of the Service)', content: `(1) The Company may add, modify, or remove any Tool or feature of the Service at its discretion in order to improve the Service, respond to changes in AI technology, or comply with law. Where a change is material, the Company shall give reasonable advance notice on the Service.

(2) The Company may temporarily suspend the Service, in whole or in part, in any of the following cases: routine or emergency maintenance; failure of telecommunications, power, hosting, or CDN services; a surge in traffic exceeding infrastructure capacity; force-majeure events such as natural disaster or war; or other operational causes that make normal provision of the Service impractical. The Company shall give advance notice of planned suspensions and prompt after-the-fact notice of unplanned ones.

(3) The Company may permanently discontinue all or a material part of the Service for legitimate business reasons, with no less than thirty (30) days' prior notice posted on the Service.

(4) Because the Service is provided free of charge and stores no User accounts or User Input, the Company shall not be liable to compensate Users for modification, suspension, or discontinuation of the Service, except where caused by the Company's wilful misconduct or gross negligence, or as otherwise required by mandatory law.` },
				{ title: 'Article 9 (Intellectual Property Rights)', content: `(1) All rights, title, and interest in and to the Service — including its design, layout, branding, logos, source code, guides, and editorial content — belong to the Company or its licensors and are protected by the copyright, trademark, and other intellectual-property laws of the Republic of Korea and other jurisdictions.

(2) The Company grants the User a limited, non-exclusive, non-transferable, revocable licence to access and use the Service for personal or internal-business purposes. The User shall not reproduce, distribute, publicly transmit, or create derivative works from the Service's editorial content, nor use it for training machine-learning models, without the Company's prior written consent.

(3) User Input remains entirely the User's. Because User Input never reaches the Company's servers, the Company claims no licence to, and has no access to, User Input.

(4) As between the Company and the User, the Company claims no ownership of AI Output, and the User may use AI Output for personal or commercial purposes at the User's own responsibility. The User acknowledges, however, that (i) the copyright status of AI-generated content varies by jurisdiction and may be limited or unavailable, (ii) similar or identical output may be generated for other users, and (iii) third-party AI services used with a generated prompt may impose their own terms on the resulting content.` },
				{ title: 'Article 10 (Limitations of AI Outputs and User Responsibility)', content: `(1) **AI Output may be inaccurate.** The Tools and the third-party AI models they are designed to be used with are based on statistical language technology. AI Output may contain factual errors, fabricated information presented with confidence ("hallucinations"), outdated information reflecting a model's training cutoff, mistranslations, faulty code, or reasoning mistakes.

(2) **AI Output may be biased.** AI models learn from large bodies of human-created text and can reproduce or amplify social, cultural, and linguistic biases present in that data. AI Output should not be treated as neutral or authoritative.

(3) **Duty to verify.** The User must independently review and verify all AI Output before relying on it, publishing it, submitting it, or otherwise acting upon it. In particular, AI Output shall not be relied upon as a substitute for professional advice in legal, medical, financial, tax, safety-critical, or other specialised matters; the User must consult a qualified professional for such matters.

(4) **No warranty.** The Company makes no representation or warranty of any kind regarding the accuracy, completeness, reliability, legality, non-infringement, or fitness for any particular purpose of any AI Output, whether produced by a Tool or by a third-party AI service using a prompt created with a Tool.

(5) **User responsibility.** The User bears sole responsibility for any decision made, action taken, content published, or damage incurred in reliance on AI Output. To the maximum extent permitted by law, the Company shall not be liable for any loss or damage arising from a User's reliance on AI Output that the User failed to verify.` },
				{ title: 'Article 11 (Disclaimer and Limitation of Liability)', content: `(1) The Service is provided "as is" and "as available", without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, and uninterrupted availability, to the maximum extent permitted by applicable law.

(2) The Company shall be exempt from liability for failure to provide the Service caused by force majeure, including natural disaster, war, terrorism, epidemics, telecommunications failure, or governmental action, or by causes attributable to the User.

(3) The Company shall not be liable for: (i) the substance, accuracy, or consequences of any AI Output; (ii) the acts, policies, availability, or output of third-party AI services (such as ChatGPT, Claude, Gemini, Midjourney, or Stable Diffusion) into which the User pastes a generated prompt; (iii) products or services advertised on the Service by third parties, with respect to which any transaction is solely between the User and the advertiser; (iv) loss of expected profit, loss of data kept only on the User's device, or damage arising from materials obtained through the Service.

(4) Except in cases of the Company's wilful misconduct or gross negligence, the Company shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising out of or in connection with the use of, or inability to use, the Service.

(5) Nothing in these Terms excludes or limits any liability that cannot be excluded or limited under applicable law, including liability arising from the Company's wilful misconduct or gross negligence.` },
				{ title: 'Article 12 (Dispute Resolution and Governing Law)', content: `(1) The Company shall prioritise the fair and prompt handling of legitimate opinions and complaints raised by Users. Complaints may be submitted to ${CONTACT_EMAIL}, and the Company shall endeavour to respond within fourteen (14) days of receipt.

(2) These Terms and the use of the Service shall be governed by and construed in accordance with the laws of the Republic of Korea, without regard to conflict-of-laws principles.

(3) Any lawsuit between the Company and a User arising out of the Service shall be brought before the competent court under the Civil Procedure Act of the Republic of Korea. Where the User is a consumer, nothing in this Article deprives the User of the protection of mandatory consumer-protection provisions, including any right to bring or defend proceedings in the forum prescribed by such provisions.

(4) Users may also seek redress through the Korea Consumer Agency or the Electronic Commerce Dispute Mediation Committee, and Users residing in the European Union may use the European Online Dispute Resolution platform at https://ec.europa.eu/consumers/odr.` },
				{ title: 'Supplementary Provision (Addendum)', content: `(1) These Terms take effect on ${EFFECTIVE_DATE} and were last amended on ${LAST_UPDATED}. The amended Terms supersede all prior versions.

(2) For questions about these Terms, contact ${CONTACT_EMAIL}.

- **Operator**: ${COMPANY_NAME}
- **Business Registration Number**: ${BUSINESS_NUMBER}
- **E-Commerce Sales Registration**: ${ECOMMERCE_NUMBER}
- **Address**: ${COMPANY_ADDRESS_EN}
- **Contact**: ${CONTACT_EMAIL}` }
			]
		},

		ko: {
			title: '이용약관',
			lastUpdated: `최종 수정일: ${LAST_UPDATED}`,
			effective: `시행일: ${EFFECTIVE_DATE}`,
			intro: `본 이용약관(이하 "약관")은 https://${SITE_DOMAIN} 에서 접속 가능한 ${SITE_NAME}(이하 "서비스")를 운영하는 ${COMPANY_NAME}(이하 "회사")와 이용자(이하 "이용자") 사이에 법적 구속력을 가지는 계약입니다. 서비스에 접속하거나 이를 이용함으로써 이용자는 본 약관과 개인정보 처리방침을 읽고 이해하였으며 이에 구속되는 데 동의함을 확인합니다. 동의하지 않는 경우 서비스 이용을 중단하여 주시기 바랍니다.`,
			sections: [
				{ title: '제1조 (목적)', content: `본 약관은 회사가 제공하는 무료 브라우저 기반 AI 유틸리티 도구 모음인 ${SITE_NAME}의 이용과 관련하여 회사와 이용자 간의 권리·의무 및 책임사항, 기타 필요한 사항을 규정함을 목적으로 합니다. 본 약관에서 정하지 아니한 사항은 「전자상거래 등에서의 소비자보호에 관한 법률」, 「정보통신망 이용촉진 및 정보보호 등에 관한 법률」, 「개인정보 보호법」 등 대한민국 관련 법령, 일반적인 상관례 및 적용 가능한 국제 법규에 따릅니다.` },
				{ title: '제2조 (정의)', content: `본 약관에서 사용하는 용어의 정의는 다음과 같습니다.

- **"회사"**란 대한민국 법률에 따라 설립된 법인 ${COMPANY_NAME}를 말합니다. 사업자등록번호 ${BUSINESS_NUMBER}, 통신판매업신고번호 ${ECOMMERCE_NUMBER}, 소재지 ${COMPANY_ADDRESS}.
- **"서비스"**란 https://${SITE_DOMAIN} 에서 호스팅되는 웹사이트, 모든 서브도메인, 그리고 회사가 이를 통해 제공하는 모든 도구, 콘텐츠, 가이드 및 관련 자료를 말합니다.
- **"이용자"**란 서비스에 접속하거나 이를 이용하는 모든 개인 또는 단체를 말합니다. 서비스는 회원가입이 필요 없으며, 모든 방문자가 이용자입니다.
- **"도구"**란 서비스를 통해 제공되는 AI 지원 유틸리티를 말하며, 현재 AI 번역기, 텍스트 요약기, 프롬프트 생성기, 이미지 프롬프트 빌더, 코드 설명기, 이메일 작성기, 해시태그 생성기, 글쓰기 도우미를 포함하고, 이후 추가되는 도구도 포함합니다.
- **"이용자 입력"**이란 이용자가 도구에 입력하는 텍스트, 코드 기타 자료를 말합니다. 이용자 입력은 이용자의 브라우저에서 처리되며 회사 서버로 전송·저장되지 않습니다.
- **"AI 출력물"**이란 이용자 입력으로부터 도구가 생성하는 프롬프트, 텍스트 기타 결과물과, 도구로 생성한 프롬프트를 이용하여 제3자 AI 서비스가 추가로 생성하는 콘텐츠를 말합니다.` },
				{ title: '제3조 (약관의 게시와 개정)', content: `① 회사는 이용자가 언제든지 쉽게 확인할 수 있도록 본 약관을 서비스에 게시합니다.

② 회사는 관련 법령을 위배하지 않는 범위에서 본 약관을 개정할 수 있습니다. 약관을 개정하는 경우 회사는 적용일자 및 개정사유를 명시하여 개정 약관을 그 적용일 7일 전부터 서비스에 공지합니다. 다만 이용자에게 불리하거나 중대한 개정의 경우에는 적용일 30일 전부터 공지합니다.

③ 개정 약관에 동의하지 않는 이용자는 적용일 전에 서비스 이용을 중단할 수 있습니다. 적용일 이후에도 서비스를 계속 이용하는 경우 개정 약관에 동의한 것으로 봅니다.` },
				{ title: '제4조 (서비스의 제공)', content: `① 회사는 광고 수익을 재원으로 하여 서비스를 무료로, "제공 가능한 상태(as available)"를 기준으로 제공합니다. 서비스는 다음을 포함하되 이에 한정되지 않습니다.

- 8종의 AI 지원 도구: AI 번역기, 텍스트 요약기, 프롬프트 생성기, 이미지 프롬프트 빌더, 코드 설명기, 이메일 작성기, 해시태그 생성기, 글쓰기 도우미
- AI 모델을 효과적으로 활용하기 위한 실용 가이드 및 참고 자료
- 9개 인터페이스 언어의 다국어 지원

② 도구는 그 로직을 이용자의 브라우저에서 실행합니다. 도구가 외부 AI 어시스턴트(ChatGPT, Claude, Gemini 등)용 프롬프트를 생성하는 경우, 해당 외부 서비스의 이용에는 본 약관이 아니라 해당 사업자의 약관이 적용됩니다.

③ 서비스는 연중무휴 1일 24시간 제공을 원칙으로 합니다. 다만 정기·긴급 점검, 통신 또는 인프라 제공업체 장애, 천재지변 기타 회사가 합리적으로 통제할 수 없는 사유가 있는 경우에는 그러하지 아니합니다.` },
				{ title: '제5조 (서비스 이용)', content: `① 이용자는 회원가입 없이 익명으로, 본 약관과 관련 법령에 따라 적법한 개인적 또는 내부 업무 목적으로 서비스를 이용할 수 있습니다.

② 서비스 이용은 이용자가 서비스에 접속함으로써 개시되며, 별도의 이용신청이나 승낙 절차는 없습니다.

③ 이용자는 이용자 입력이 전적으로 이용자 본인의 기기에서 처리되어 회사 서버에 도달하지 않으며, 따라서 회사가 이용자를 대신하여 이용자 입력을 복구·복원·삭제할 수 없음을 인지합니다.

④ 이용자는 각 도구 페이지에 표시되는 AI 한계 관련 주의사항을 포함하여, 회사가 서비스에 게시하는 운영정책, 이용 안내 및 주의사항을 준수하여야 합니다.` },
				{ title: '제6조 (이용자의 의무)', content: `이용자는 다음 각 호의 의무를 부담합니다.

1. 관련 법령, 본 약관 및 서비스에 게시된 이용 안내를 준수할 것
2. AI 출력물에 의존하거나 이를 게시하기 전에 제10조에 따라 그 정확성·적법성·적합성을 스스로 검증할 것
3. 도구에 입력하는 텍스트, 코드 기타 자료에 관하여 필요한 모든 권리를 보유하고 있으며, 그 입력이 제3자의 권리를 침해하거나 비밀유지의무를 위반하지 않음을 보증할 것
4. 타인을 오도할 수 있는 상황에서 AI 출력물을 독립적으로 검증된 사실, 전문가의 조언 또는 인간 전문가의 저작물인 것처럼 표시하지 않을 것
5. 서비스 및 AI 출력물의 이용(게시·배포·상업적 이용 포함)으로 인한 결과에 대하여 스스로 책임을 부담할 것
6. 서비스의 운영을 방해하거나 회사 또는 다른 이용자의 명예를 훼손하지 않을 것` },
				{ title: '제7조 (금지행위)', content: `이용자는 다음 각 호의 행위를 하여서는 안 됩니다.

1. 불법적이거나 사기적, 명예훼손적, 괴롭힘, 혐오, 차별, 성착취적이거나 폭력·자해를 조장하는 콘텐츠를 생성·다듬기·최적화하기 위해 도구를 이용하는 행위
2. 피싱 메시지, 사기성 이메일, 대중을 오도하기 위한 허위정보, 타인 또는 타 기관 사칭 등 기만적 콘텐츠를 만들기 위해 도구를 이용하는 행위
3. 제3자의 저작권, 상표권, 영업비밀, 프라이버시권, 퍼블리시티권 침해를 조장하기 위해 도구를 이용하는 행위
4. 자동화된 스크래핑, robots.txt가 허용하는 범위를 초과하는 대량 크롤링, 기술적 보호조치 우회 등 비정상적인 방법으로 서비스에 접근하거나 접근을 시도하는 행위
5. 바이러스, 악성코드 기타 서비스 또는 제3자 시스템을 방해·손상시키도록 설계된 코드를 전송·배포하는 행위
6. 서비스의 광고, 분석, 보안 기능 기타 기술적 구성요소를 방해하거나, 광고 노출·클릭을 인위적으로 발생시키는 행위
7. 서비스 인프라에 불합리한 부하를 발생시키거나 다른 이용자의 이용 경험을 현저히 저해하는 행위
8. 서비스 자체를 재판매·재라이선스하거나 이용자 자신의 제품·서비스인 것처럼 표시하는 행위
9. 기타 관련 법령, 공공질서 또는 미풍양속에 위반되는 행위

회사는 이용자가 금지행위를 하였다고 합리적으로 판단하는 경우, 사전 통지 여부와 관계없이 접속 제한·차단(속도 제한, IP 차단 등) 조치를 취할 수 있으며, 필요한 경우 수사기관에 관련 사실을 통보할 수 있습니다. 조치를 받은 이용자는 ${CONTACT_EMAIL} 로 서면 이의를 제기할 수 있으며, 회사는 접수일로부터 14일 이내에 성실히 검토합니다.` },
				{ title: '제8조 (서비스의 변경 및 중단)', content: `① 회사는 서비스 개선, AI 기술 변화에 대한 대응 또는 법령 준수를 위하여 재량으로 도구나 기능을 추가·변경·삭제할 수 있습니다. 변경이 중대한 경우 회사는 서비스에 상당한 기간을 두고 사전 공지합니다.

② 회사는 다음 각 호의 경우 서비스의 전부 또는 일부 제공을 일시적으로 중단할 수 있습니다: 정기 또는 긴급 점검; 통신·전력·호스팅·CDN 서비스의 장애; 인프라 용량을 초과하는 트래픽 급증; 천재지변, 전쟁 등 불가항력; 기타 정상적인 서비스 제공이 곤란한 운영상의 사유. 계획된 중단은 사전에, 계획되지 않은 중단은 사후에 지체 없이 공지합니다.

③ 회사는 정당한 경영상의 사유가 있는 경우 30일 이상의 사전 공지를 거쳐 서비스의 전부 또는 중요한 일부를 영구적으로 종료할 수 있습니다.

④ 서비스는 무료로 제공되고 이용자 계정이나 이용자 입력을 저장하지 않으므로, 회사의 고의 또는 중대한 과실로 인한 경우 및 강행법규가 달리 정하는 경우를 제외하고, 회사는 서비스의 변경·중단·종료에 대하여 이용자에게 배상 책임을 부담하지 않습니다.` },
				{ title: '제9조 (지식재산권)', content: `① 서비스의 디자인, 레이아웃, 브랜딩, 로고, 소스코드, 가이드 및 편집 콘텐츠를 포함한 서비스에 관한 일체의 권리는 회사 또는 그 라이선서에게 귀속되며, 대한민국 및 기타 국가의 저작권법, 상표법 등 지식재산권 법령의 보호를 받습니다.

② 회사는 이용자에게 개인적 또는 내부 업무 목적으로 서비스에 접근·이용할 수 있는 제한적, 비독점적, 양도 불가능하고 철회 가능한 이용권을 부여합니다. 이용자는 회사의 사전 서면 동의 없이 서비스의 편집 콘텐츠를 복제·배포·공중송신하거나 2차적 저작물을 작성할 수 없으며, 기계학습 모델의 학습에 이용할 수 없습니다.

③ 이용자 입력에 관한 권리는 전적으로 이용자에게 있습니다. 이용자 입력은 회사 서버에 도달하지 않으므로, 회사는 이용자 입력에 대하여 어떠한 라이선스도 주장하지 않으며 접근 권한도 없습니다.

④ 회사와 이용자 사이에서 회사는 AI 출력물에 대한 소유권을 주장하지 않으며, 이용자는 자신의 책임 하에 AI 출력물을 개인적 또는 상업적 목적으로 이용할 수 있습니다. 다만 이용자는 (i) AI 생성 콘텐츠의 저작권 인정 여부는 국가별로 다르며 제한되거나 인정되지 않을 수 있다는 점, (ii) 다른 이용자에게 유사하거나 동일한 출력물이 생성될 수 있다는 점, (iii) 생성된 프롬프트와 함께 사용되는 제3자 AI 서비스가 결과 콘텐츠에 자체 약관을 적용할 수 있다는 점을 인지합니다.` },
				{ title: '제10조 (AI 출력물의 한계와 이용자의 책임)', content: `① **AI 출력물은 부정확할 수 있습니다.** 도구 및 도구와 함께 사용하도록 설계된 제3자 AI 모델은 통계적 언어 기술에 기반합니다. AI 출력물에는 사실 오류, 그럴듯하게 지어낸 정보("환각, hallucination"), 모델 학습 시점의 한계로 인한 오래된 정보, 오역, 결함 있는 코드, 추론 오류가 포함될 수 있습니다.

② **AI 출력물은 편향될 수 있습니다.** AI 모델은 인간이 작성한 방대한 텍스트로부터 학습하므로, 그 데이터에 존재하는 사회적·문화적·언어적 편향을 재현하거나 증폭할 수 있습니다. AI 출력물을 중립적이거나 권위 있는 것으로 취급해서는 안 됩니다.

③ **검증 의무.** 이용자는 AI 출력물에 의존하거나 이를 게시·제출하거나 이에 기초하여 행동하기 전에 반드시 스스로 검토·검증하여야 합니다. 특히 법률, 의료, 금융, 세무, 안전에 중대한 영향을 미치는 사안 기타 전문 분야에서 AI 출력물을 전문가 조언의 대체물로 삼아서는 안 되며, 반드시 해당 분야의 자격 있는 전문가와 상담하여야 합니다.

④ **무보증.** 회사는 도구가 생성한 것이든 도구로 만든 프롬프트를 이용하여 제3자 AI 서비스가 생성한 것이든, AI 출력물의 정확성, 완전성, 신뢰성, 적법성, 비침해성 또는 특정 목적 적합성에 관하여 어떠한 진술이나 보증도 하지 않습니다.

⑤ **이용자의 책임.** AI 출력물에 의존하여 내린 결정, 취한 행동, 게시한 콘텐츠 및 발생한 손해에 대한 책임은 전적으로 이용자에게 있습니다. 법령이 허용하는 최대 범위 내에서, 회사는 이용자가 검증하지 않은 AI 출력물에 의존함으로써 발생한 손실이나 손해에 대하여 책임을 지지 않습니다.` },
				{ title: '제11조 (면책조항)', content: `① 서비스는 법령이 허용하는 최대 범위 내에서 상품성, 특정 목적 적합성, 비침해성, 정확성, 중단 없는 이용 가능성에 대한 보증을 포함한 명시적·묵시적 보증 없이 "있는 그대로(as is)", "제공 가능한 상태(as available)"로 제공됩니다.

② 회사는 천재지변, 전쟁, 테러, 감염병, 통신 장애, 정부의 조치 등 불가항력 또는 이용자의 귀책사유로 인하여 서비스를 제공할 수 없는 경우 그 책임이 면제됩니다.

③ 회사는 다음 각 호에 대하여 책임을 지지 않습니다: (i) AI 출력물의 내용, 정확성 또는 그로 인한 결과; (ii) 이용자가 생성된 프롬프트를 붙여넣는 제3자 AI 서비스(ChatGPT, Claude, Gemini, Midjourney, Stable Diffusion 등)의 행위, 정책, 가용성 또는 출력물; (iii) 서비스에 게재된 제3자 광고 상품·서비스 — 관련 거래는 전적으로 이용자와 광고주 사이의 문제입니다; (iv) 이용자의 기대수익 상실, 이용자 기기에만 보관된 데이터의 손실, 서비스를 통해 얻은 자료로 인한 손해.

④ 회사는 회사의 고의 또는 중대한 과실이 없는 한 간접손해, 부수적 손해, 특별손해, 결과적 손해 또는 징벌적 손해에 대하여 책임을 지지 않습니다.

⑤ 본 약관의 어떠한 조항도 회사의 고의 또는 중대한 과실로 인한 책임 등 관련 법령상 배제하거나 제한할 수 없는 책임을 배제하거나 제한하지 않습니다.` },
				{ title: '제12조 (분쟁해결 및 준거법)', content: `① 회사는 이용자가 제기하는 정당한 의견이나 불만을 공정하고 신속하게 처리하기 위하여 노력합니다. 불만사항은 ${CONTACT_EMAIL} 로 접수할 수 있으며, 회사는 접수일로부터 14일 이내에 회신하도록 노력합니다.

② 본 약관 및 서비스 이용에는 국제사법 원칙에 불구하고 대한민국 법령이 적용됩니다.

③ 서비스 이용과 관련하여 회사와 이용자 사이에 발생한 소송은 「민사소송법」상의 관할법원에 제기합니다. 이용자가 소비자인 경우, 본 조의 어떠한 내용도 소비자보호 관련 강행규정이 정하는 관할에서 소를 제기하거나 응소할 권리 등 해당 규정에 따른 보호를 박탈하지 않습니다.

④ 이용자는 한국소비자원 또는 전자거래분쟁조정위원회를 통한 피해구제를 신청할 수 있으며, 유럽연합에 거주하는 이용자는 유럽 온라인 분쟁해결 플랫폼(https://ec.europa.eu/consumers/odr)을 이용할 수 있습니다.` },
				{ title: '부칙', content: `① 본 약관은 ${EFFECTIVE_DATE}부터 시행되며, ${LAST_UPDATED}에 최종 개정되었습니다. 개정된 약관은 이전의 모든 버전을 대체합니다.

② 본 약관에 관한 문의는 ${CONTACT_EMAIL} 로 연락 주시기 바랍니다.

- **상호**: ${COMPANY_NAME}
- **사업자등록번호**: ${BUSINESS_NUMBER}
- **통신판매업신고번호**: ${ECOMMERCE_NUMBER}
- **주소**: ${COMPANY_ADDRESS}
- **연락처**: ${CONTACT_EMAIL}` }
			]
		},

		ja: {
			title: '利用規約',
			lastUpdated: `最終更新日: ${LAST_UPDATED}`,
			effective: `施行日: ${EFFECTIVE_DATE}`,
			intro: `本利用規約(以下「本規約」)は、https://${SITE_DOMAIN} でアクセスできる ${SITE_NAME}(以下「本サービス」)を運営する ${COMPANY_NAME}(以下「当社」)と、利用者(以下「ユーザー」)との間の法的拘束力を有する契約です。本サービスにアクセスまたはこれを利用することにより、ユーザーは本規約およびプライバシーポリシーを読み、理解し、これに拘束されることに同意したものとみなされます。同意いただけない場合は、本サービスの利用を中止してください。`,
			sections: [
				{ title: '第1条(目的)', content: `本規約は、当社が提供する無料のブラウザベース AI ユーティリティツール集である ${SITE_NAME} の利用に関して、当社とユーザーとの間の権利・義務・責任事項その他必要な事項を定めることを目的とします。本規約に定めのない事項については、電子商取引等における消費者保護に関する法律、情報通信網利用促進及び情報保護等に関する法律、個人情報保護法をはじめとする大韓民国の関係法令、一般的な商慣習および適用可能な国際法規に従います。` },
				{ title: '第2条(定義)', content: `本規約における用語の定義は次のとおりです。

- **「当社」**とは、大韓民国の法律に基づき設立された法人 ${COMPANY_NAME} をいいます。事業者登録番号 ${BUSINESS_NUMBER}、通信販売業届出番号 ${ECOMMERCE_NUMBER}、所在地 ${COMPANY_ADDRESS_EN}。
- **「本サービス」**とは、https://${SITE_DOMAIN} でホストされるウェブサイト、すべてのサブドメイン、および当社がこれを通じて提供するすべてのツール、コンテンツ、ガイド、関連資料をいいます。
- **「ユーザー」**とは、本サービスにアクセスしまたはこれを利用するすべての個人または団体をいいます。本サービスは登録不要であり、すべての訪問者がユーザーです。
- **「ツール」**とは、本サービスを通じて提供される AI 支援ユーティリティをいい、現在、AI 翻訳、テキスト要約、プロンプト生成、画像プロンプトビルダー、コード解説、メール作成、ハッシュタグ生成、ライティングアシスタントを含み、今後追加されるツールも含みます。
- **「ユーザー入力」**とは、ユーザーがツールに入力するテキスト、コードその他の資料をいいます。ユーザー入力はユーザーのブラウザ内で処理され、当社サーバーへ送信・保存されません。
- **「AI 出力物」**とは、ユーザー入力からツールが生成するプロンプト、テキストその他の成果物、およびツールで作成したプロンプトを用いて第三者の AI サービスがさらに生成するコンテンツをいいます。` },
				{ title: '第3条(規約の掲示と改定)', content: `(1) 当社は、ユーザーがいつでも容易に確認できるよう、本規約を本サービス上に掲示します。

(2) 当社は、関係法令に違反しない範囲で本規約を改定することができます。規約を改定する場合、当社は適用日および改定理由を明示し、改定後の規約を適用日の 7 日前から本サービス上に告知します。ただし、ユーザーに不利益となる、または重大な改定の場合は、適用日の 30 日前から告知します。

(3) 改定規約に同意しないユーザーは、適用日前に本サービスの利用を中止することができます。適用日以降も本サービスの利用を継続した場合、改定規約に同意したものとみなされます。` },
				{ title: '第4条(本サービスの提供)', content: `(1) 当社は、広告収入を財源として本サービスを無料で、「提供可能な状態(as available)」を基準に提供します。本サービスには以下が含まれますが、これらに限られません。

- 8 種の AI 支援ツール: AI 翻訳、テキスト要約、プロンプト生成、画像プロンプトビルダー、コード解説、メール作成、ハッシュタグ生成、ライティングアシスタント
- AI モデルを効果的に活用するための実用ガイドおよび参考資料
- 9 つのインターフェース言語による多言語対応

(2) ツールはそのロジックをユーザーのブラウザ内で実行します。ツールが外部 AI アシスタント(ChatGPT、Claude、Gemini 等)向けのプロンプトを生成する場合、当該外部サービスの利用には本規約ではなく当該事業者の規約が適用されます。

(3) 本サービスは、年中無休・1 日 24 時間の提供を原則とします。ただし、定期・緊急メンテナンス、通信またはインフラ事業者の障害、天災地変その他当社が合理的に制御できない事由がある場合はこの限りではありません。` },
				{ title: '第5条(本サービスの利用)', content: `(1) ユーザーは、登録なしに匿名で、本規約および関係法令に従い、適法な個人的または社内業務の目的で本サービスを利用することができます。

(2) 本サービスの利用は、ユーザーが本サービスにアクセスした時点で開始され、別途の申込みや承諾手続はありません。

(3) ユーザーは、ユーザー入力が専らユーザー自身の端末上で処理され当社サーバーに到達しないこと、したがって当社がユーザーに代わってユーザー入力を復旧・復元・削除できないことを了承します。

(4) ユーザーは、各ツールページに表示される AI の限界に関する注意事項を含め、当社が本サービス上に掲示する運営ポリシー、利用案内および注意事項を遵守しなければなりません。` },
				{ title: '第6条(ユーザーの義務)', content: `ユーザーは、次の各号の義務を負います。

1. 関係法令、本規約および本サービス上に掲示された利用案内を遵守すること
2. AI 出力物に依拠しまたはこれを公開する前に、第 10 条に従いその正確性・適法性・適合性を自ら検証すること
3. ツールに入力するテキスト、コードその他の資料について必要なすべての権利を保有しており、その入力が第三者の権利を侵害せず、守秘義務にも違反しないことを保証すること
4. 他者を誤認させるおそれのある状況で、AI 出力物を独立に検証された事実、専門家の助言または人間の専門家の著作物であるかのように表示しないこと
5. 本サービスおよび AI 出力物の利用(公開・配布・商用利用を含む)による結果について自ら責任を負うこと
6. 本サービスの運営を妨害し、または当社もしくは他のユーザーの名誉を毀損しないこと` },
				{ title: '第7条(禁止行為)', content: `ユーザーは、次の各号の行為をしてはなりません。

1. 違法、詐欺的、名誉毀損的、嫌がらせ、憎悪、差別、性的搾取に当たるコンテンツ、または暴力・自傷を助長するコンテンツを作成・改良・最適化するためにツールを利用する行為
2. フィッシングメッセージ、詐欺メール、公衆を誤導するための偽情報、他人または他組織のなりすまし等、欺瞞的コンテンツを作成するためにツールを利用する行為
3. 第三者の著作権、商標権、営業秘密、プライバシー権、パブリシティ権の侵害を助長するためにツールを利用する行為
4. 自動スクレイピング、robots.txt が許容する範囲を超える大量クロール、技術的保護手段の回避など、異常な方法で本サービスにアクセスしまたはアクセスを試みる行為
5. ウイルス、マルウェアその他本サービスまたは第三者のシステムを妨害・損傷するよう設計されたコードを送信・配布する行為
6. 本サービスの広告、分析、セキュリティ機能その他の技術的構成要素を妨害し、または広告の表示・クリックを人為的に発生させる行為
7. 本サービスのインフラに不合理な負荷をかけ、または他のユーザーの利用体験を著しく損なう行為
8. 本サービス自体を再販売・再許諾し、またはユーザー自身の製品・サービスであるかのように表示する行為
9. その他、関係法令、公序良俗に違反する行為

当社は、ユーザーが禁止行為を行ったと合理的に判断する場合、事前通知の有無にかかわらず、アクセスの制限・遮断(レート制限、IP ブロック等)の措置を講じることができ、必要な場合は捜査機関に関連事実を通報することがあります。措置を受けたユーザーは ${CONTACT_EMAIL} 宛てに書面で異議を申し立てることができ、当社は受領日から 14 日以内に誠実に検討します。` },
				{ title: '第8条(本サービスの変更および中断)', content: `(1) 当社は、本サービスの改善、AI 技術の変化への対応または法令遵守のため、裁量によりツールや機能を追加・変更・削除することができます。変更が重大な場合、当社は相当な期間をおいて本サービス上で事前に告知します。

(2) 当社は、次の各号の場合、本サービスの全部または一部の提供を一時的に中断することができます: 定期または緊急メンテナンス; 通信・電力・ホスティング・CDN サービスの障害; インフラ容量を超えるトラフィックの急増; 天災地変、戦争等の不可抗力; その他、通常のサービス提供が困難な運営上の事由。計画された中断は事前に、計画外の中断は事後遅滞なく告知します。

(3) 当社は、正当な経営上の理由がある場合、30 日以上前の事前告知を経て、本サービスの全部または重要な一部を恒久的に終了することができます。

(4) 本サービスは無料で提供され、ユーザーアカウントもユーザー入力も保存しないため、当社の故意または重大な過失による場合および強行法規が別段の定めをする場合を除き、当社は本サービスの変更・中断・終了についてユーザーに対する賠償責任を負いません。` },
				{ title: '第9条(知的財産権)', content: `(1) 本サービスのデザイン、レイアウト、ブランディング、ロゴ、ソースコード、ガイドおよび編集コンテンツを含む本サービスに関する一切の権利は、当社またはそのライセンサーに帰属し、大韓民国およびその他の国の著作権法、商標法その他の知的財産権法により保護されます。

(2) 当社は、ユーザーに対し、個人的または社内業務の目的で本サービスにアクセスし利用するための、限定的、非独占的、譲渡不能かつ取消可能な利用権を付与します。ユーザーは、当社の事前の書面による同意なく、本サービスの編集コンテンツを複製・配布・公衆送信し、二次的著作物を作成し、または機械学習モデルの学習に利用してはなりません。

(3) ユーザー入力に関する権利は、完全にユーザーに帰属します。ユーザー入力は当社サーバーに到達しないため、当社はユーザー入力についていかなるライセンスも主張せず、アクセス権も有しません。

(4) 当社とユーザーの間において、当社は AI 出力物の所有権を主張せず、ユーザーは自己の責任において AI 出力物を個人的または商業的目的で利用することができます。ただし、ユーザーは、(i) AI 生成コンテンツの著作権の扱いは国・地域により異なり、制限されまたは認められない場合があること、(ii) 他のユーザーに類似または同一の出力物が生成される可能性があること、(iii) 生成されたプロンプトとともに利用する第三者 AI サービスが、その成果物に独自の規約を適用する場合があることを了承します。` },
				{ title: '第10条(AI 出力物の限界とユーザーの責任)', content: `(1) **AI 出力物は不正確な場合があります。** ツールおよびツールとともに使用されるよう設計された第三者の AI モデルは、統計的言語技術に基づいています。AI 出力物には、事実誤認、もっともらしく捏造された情報(「ハルシネーション」)、モデルの学習時点の限界による古い情報、誤訳、欠陥のあるコード、推論の誤りが含まれる可能性があります。

(2) **AI 出力物には偏りが含まれる場合があります。** AI モデルは人間が作成した膨大なテキストから学習するため、そのデータに存在する社会的・文化的・言語的バイアスを再現または増幅することがあります。AI 出力物を中立的または権威あるものとして扱ってはなりません。

(3) **検証義務。** ユーザーは、AI 出力物に依拠し、これを公開・提出し、またはこれに基づいて行動する前に、必ず自ら確認・検証しなければなりません。特に、法律、医療、金融、税務、安全に重大な影響を及ぼす事項その他の専門分野において、AI 出力物を専門家の助言の代替としてはならず、必ず当該分野の資格を有する専門家に相談してください。

(4) **無保証。** 当社は、ツールが生成したものであるか、ツールで作成したプロンプトを用いて第三者 AI サービスが生成したものであるかを問わず、AI 出力物の正確性、完全性、信頼性、適法性、非侵害性または特定目的への適合性について、いかなる表明も保証も行いません。

(5) **ユーザーの責任。** AI 出力物に依拠して行った決定、行動、公開したコンテンツおよび被った損害についての責任は、すべてユーザーが負います。法令が許容する最大限の範囲で、当社は、ユーザーが検証を怠った AI 出力物への依拠から生じた損失・損害について責任を負いません。` },
				{ title: '第11条(免責事項)', content: `(1) 本サービスは、法令が許容する最大限の範囲で、商品性、特定目的への適合性、非侵害性、正確性、中断のない利用可能性に関する保証を含む明示・黙示のいかなる保証もなく、「現状のまま(as is)」かつ「提供可能な状態(as available)」で提供されます。

(2) 当社は、天災地変、戦争、テロ、感染症、通信障害、政府の措置等の不可抗力またはユーザーの帰責事由により本サービスを提供できない場合、その責任を免れます。

(3) 当社は、次の各号について責任を負いません: (i) AI 出力物の内容、正確性またはそれによる結果; (ii) ユーザーが生成されたプロンプトを貼り付ける第三者 AI サービス(ChatGPT、Claude、Gemini、Midjourney、Stable Diffusion 等)の行為、ポリシー、可用性または出力物; (iii) 本サービス上に掲載された第三者の広告商品・サービス — 関連する取引は専らユーザーと広告主との間の問題です; (iv) ユーザーの期待利益の喪失、ユーザーの端末にのみ保存されたデータの損失、本サービスを通じて得た資料による損害。

(4) 当社は、当社に故意または重大な過失がない限り、間接損害、付随的損害、特別損害、結果的損害または懲罰的損害について責任を負いません。

(5) 本規約のいかなる条項も、当社の故意または重大な過失による責任など、適用法令上排除または制限できない責任を排除または制限するものではありません。` },
				{ title: '第12条(紛争解決および準拠法)', content: `(1) 当社は、ユーザーが提起する正当な意見や苦情を公正かつ迅速に処理するよう努めます。苦情は ${CONTACT_EMAIL} で受け付けており、当社は受領日から 14 日以内の回答に努めます。

(2) 本規約および本サービスの利用には、抵触法の原則にかかわらず、大韓民国の法令が適用されます。

(3) 本サービスに関して当社とユーザーとの間で生じた訴訟は、大韓民国民事訴訟法上の管轄裁判所に提起します。ユーザーが消費者である場合、本条のいかなる内容も、消費者保護に関する強行規定が定める管轄で訴えを提起しまたは応訴する権利など、当該規定による保護を奪うものではありません。

(4) ユーザーは、韓国消費者院または電子取引紛争調停委員会を通じた被害救済を申請することができ、欧州連合に居住するユーザーは欧州オンライン紛争解決プラットフォーム(https://ec.europa.eu/consumers/odr)を利用できます。` },
				{ title: '附則', content: `(1) 本規約は ${EFFECTIVE_DATE} から施行され、${LAST_UPDATED} に最終改定されました。改定後の規約は、それ以前のすべてのバージョンに優先します。

(2) 本規約に関するお問い合わせは ${CONTACT_EMAIL} までご連絡ください。

- **事業者名**: ${COMPANY_NAME}
- **事業者登録番号**: ${BUSINESS_NUMBER}
- **通信販売業届出番号**: ${ECOMMERCE_NUMBER}
- **住所**: ${COMPANY_ADDRESS_EN}
- **連絡先**: ${CONTACT_EMAIL}` }
			]
		},

		zh: {
			title: '服务条款',
			lastUpdated: `最后更新：${LAST_UPDATED}`,
			effective: `生效日期：${EFFECTIVE_DATE}`,
			intro: `本服务条款（以下称"本条款"）是您（以下称"用户"）与 ${SITE_NAME}（可通过 https://${SITE_DOMAIN} 访问，以下称"本服务"）的运营者 ${COMPANY_NAME}（以下称"公司"）之间具有法律约束力的协议。访问或使用本服务，即表示您确认已阅读、理解并同意受本条款及我们的隐私政策约束。如果您不同意本条款，请停止使用本服务。`,
			sections: [
				{ title: '第一条（目的）', content: `本条款旨在就公司提供的免费浏览器端 AI 实用工具集 ${SITE_NAME} 的使用，规定公司与用户之间的权利、义务、责任及其他必要事项。本条款未尽事宜，依照大韩民国相关法律 —— 包括《电子商务消费者保护法》《信息通信网利用促进及信息保护法》《个人信息保护法》—— 以及公认的行业惯例和可适用的国际法规处理。` },
				{ title: '第二条（定义）', content: `本条款中使用的术语定义如下：

- **"公司"**指依大韩民国法律设立的法人 ${COMPANY_NAME}，营业执照登记号 ${BUSINESS_NUMBER}，通信销售业申报号 ${ECOMMERCE_NUMBER}，地址为 ${COMPANY_ADDRESS_EN}。
- **"本服务"**指托管于 https://${SITE_DOMAIN} 的网站、所有子域名，以及公司通过其提供的全部工具、内容、指南和相关资料。
- **"用户"**指访问或使用本服务的任何个人或实体。本服务无需注册，每一位访问者都是用户。
- **"工具"**指通过本服务提供的 AI 辅助实用程序，目前包括 AI 翻译器、文本摘要器、提示词生成器、图像提示词构建器、代码解释器、邮件写作器、标签生成器和写作助手，以及此后新增的工具。
- **"用户输入"**指用户在工具中输入的文本、代码或其他材料。用户输入在用户的浏览器中处理，不会传输至或存储于公司服务器。
- **"AI 输出"**指工具根据用户输入生成的提示词、文本或其他结果，以及第三方 AI 服务基于工具生成的提示词进一步生成的内容。` },
				{ title: '第三条（条款的公示与修订）', content: `（一）公司应将本条款公示于本服务上，以便用户随时查阅。

（二）公司可以在不违反适用法律的范围内修订本条款。修订时，公司应注明适用日期和修订理由，并自适用日期七（7）日前起在本服务上公告修订后的条款；若修订内容对用户不利或属重大修订，则至少提前三十（30）日公告。

（三）不同意修订条款的用户可以在适用日期之前停止使用本服务。在适用日期之后继续使用本服务的，视为同意修订后的条款。` },
				{ title: '第四条（服务的提供）', content: `（一）公司以广告收入为经费来源，按"可提供状态（as available）"免费提供本服务。本服务包括但不限于：

- 八款 AI 辅助工具：AI 翻译器、文本摘要器、提示词生成器、图像提示词构建器、代码解释器、邮件写作器、标签生成器、写作助手
- 有效使用 AI 模型的实用指南和参考资料
- 覆盖九种界面语言的多语言支持

（二）工具的逻辑在用户的浏览器中运行。当工具生成供外部 AI 助手（如 ChatGPT、Claude、Gemini）使用的提示词时，用户对该外部服务的使用受该提供商自身条款约束，而非本条款。

（三）本服务原则上全年无休、每天 24 小时提供。但因例行或紧急维护、电信或基础设施提供商故障、不可抗力事件或其他公司无法合理控制的情形除外。` },
				{ title: '第五条（服务的使用）', content: `（一）用户可以匿名、无需注册地使用本服务，用于符合本条款和适用法律的合法个人或内部业务目的。

（二）服务的使用自用户访问本服务时开始，无需另行申请或批准。

（三）用户知悉：用户输入完全在用户自己的设备上处理，不会到达公司服务器，因此公司无法代用户恢复、还原或删除用户输入。

（四）用户应遵守公司在本服务上发布的运营政策、使用说明和注意事项，包括各工具页面上显示的关于 AI 局限性的提示。` },
				{ title: '第六条（用户的义务）', content: `用户承担以下义务：

1. 遵守适用法律、本条款及本服务上发布的使用指引；
2. 在依赖或发布任何 AI 输出之前，按照第十条的规定自行核实其准确性、合法性和适用性；
3. 保证对输入工具的文本、代码或其他材料拥有一切必要权利，且该输入不侵犯任何第三方权利、不违反任何保密义务；
4. 在可能误导他人的情况下，不得将 AI 输出表述为经独立核实的事实、专业意见或人类专家的作品；
5. 对使用本服务及 AI 输出（包括发布、传播或商业使用）所产生的后果自行承担全部责任；
6. 不得干扰本服务的运营，不得损害公司或其他用户的名誉。` },
				{ title: '第七条（禁止行为）', content: `用户不得实施下列任何行为：

1. 使用工具创建、润色或优化违法、欺诈、诽谤、骚扰、仇恨、歧视、性剥削或宣扬暴力、自残的内容；
2. 使用工具制作欺骗性内容，包括钓鱼信息、诈骗邮件、意图误导公众的虚假信息，或冒充任何个人或组织；
3. 使用工具协助侵犯任何第三方的著作权、商标权、商业秘密、隐私权或形象权；
4. 以异常方式访问或试图访问本服务，包括自动抓取、超出 robots.txt 许可范围的大规模爬取或规避技术保护措施；
5. 传输或散布病毒、恶意软件或任何旨在破坏、损害本服务或第三方系统的代码；
6. 干扰本服务的广告、分析、安全功能或其他技术组件，或人为制造广告展示或点击；
7. 对本服务基础设施造成不合理负载，或严重损害其他用户的使用体验；
8. 转售、再许可本服务，或将本服务谎称为用户自己的产品或服务；
9. 其他违反适用法律、公共秩序或善良风俗的行为。

如果公司合理判断用户实施了禁止行为，公司可以在通知或不通知的情况下限制或阻断该用户的访问（如限速、封锁 IP），必要时可将相关事实移交执法机关。受到该等措施的用户可以向 ${CONTACT_EMAIL} 提出书面异议，公司将在收到后十四（14）日内善意审查。` },
				{ title: '第八条（服务的变更与中断）', content: `（一）为改进服务、应对 AI 技术变化或遵守法律，公司可以自行决定新增、变更或删除任何工具或功能。变更属重大时，公司将在本服务上以合理的提前期公告。

（二）在下列情形下，公司可以临时中断本服务的全部或部分：例行或紧急维护；电信、电力、托管或 CDN 服务故障；流量激增超出基础设施容量；自然灾害、战争等不可抗力；其他导致正常提供服务确有困难的运营原因。计划中断将提前公告，计划外中断将在事后及时公告。

（三）出于正当经营原因，公司可以在提前三十（30）日以上于本服务上公告后，永久终止本服务的全部或重要部分。

（四）鉴于本服务免费提供，且不保存用户账户或用户输入，除因公司故意或重大过失所致，或强制性法律另有规定外，公司不就服务的变更、中断或终止向用户承担赔偿责任。` },
				{ title: '第九条（知识产权）', content: `（一）本服务的一切权利 —— 包括其设计、布局、品牌、标识、源代码、指南和编辑内容 —— 归公司或其许可方所有，受大韩民国及其他司法辖区的著作权法、商标法及其他知识产权法律保护。

（二）公司授予用户为个人或内部业务目的访问和使用本服务的有限的、非排他的、不可转让的、可撤销的许可。未经公司事先书面同意，用户不得复制、传播、公开传输本服务的编辑内容或据其创作衍生作品，亦不得将其用于机器学习模型的训练。

（三）用户输入的权利完全归用户所有。由于用户输入从不到达公司服务器，公司对用户输入不主张任何许可，也无权访问。

（四）在公司与用户之间，公司不主张对 AI 输出的所有权，用户可以自担责任地将 AI 输出用于个人或商业目的。但用户知悉：(i) AI 生成内容的著作权地位因司法辖区而异，可能受限或不被承认；(ii) 其他用户可能获得相似或相同的输出；(iii) 与生成的提示词配合使用的第三方 AI 服务可能对其产出内容适用自己的条款。` },
				{ title: '第十条（AI 输出的局限性与用户责任）', content: `（一）**AI 输出可能不准确。** 工具及其配套使用的第三方 AI 模型基于统计语言技术。AI 输出可能包含事实错误、以自信口吻编造的信息（"幻觉"）、因模型训练截止日期而过时的信息、误译、有缺陷的代码或推理错误。

（二）**AI 输出可能存在偏见。** AI 模型从大量人类创作的文本中学习，可能复制或放大数据中存在的社会、文化和语言偏见。不应将 AI 输出视为中立或权威。

（三）**核实义务。** 用户在依赖、发布、提交任何 AI 输出或据其采取行动之前，必须自行审查和核实。特别是，在法律、医疗、金融、税务、安全攸关或其他专业事项上，不得以 AI 输出替代专业意见；此类事项必须咨询具备资质的专业人士。

（四）**不作保证。** 无论 AI 输出由工具生成，还是由第三方 AI 服务基于工具创建的提示词生成，公司均不对其准确性、完整性、可靠性、合法性、非侵权性或特定用途适用性作出任何陈述或保证。

（五）**用户责任。** 因依赖 AI 输出而作出的决定、采取的行动、发布的内容及遭受的损害，均由用户独自承担责任。在法律允许的最大范围内，公司不对用户因依赖未经核实的 AI 输出而产生的任何损失或损害承担责任。` },
				{ title: '第十一条（免责条款）', content: `（一）在适用法律允许的最大范围内，本服务按"现状（as is）"和"可提供状态（as available）"提供，不附带任何明示或默示的保证，包括对适销性、特定用途适用性、非侵权性、准确性和不间断可用性的保证。

（二）因自然灾害、战争、恐怖活动、疫情、通信故障、政府行为等不可抗力，或因可归责于用户的事由导致无法提供本服务的，公司免除责任。

（三）公司对下列事项不承担责任：(i) AI 输出的内容、准确性或由此产生的后果；(ii) 用户粘贴生成的提示词所使用的第三方 AI 服务（如 ChatGPT、Claude、Gemini、Midjourney、Stable Diffusion）的行为、政策、可用性或输出；(iii) 第三方在本服务上投放广告的商品或服务 —— 相关交易完全是用户与广告主之间的事务；(iv) 用户预期利益的丧失、仅保存在用户设备上的数据的丢失，以及因通过本服务获得的资料而产生的损害。

（四）除公司存在故意或重大过失外，公司不对间接损害、附带损害、特别损害、后果性损害或惩罚性损害承担责任。

（五）本条款的任何内容均不排除或限制依适用法律不得排除或限制的责任，包括因公司故意或重大过失而产生的责任。` },
				{ title: '第十二条（争议解决与准据法）', content: `（一）公司将努力公正、迅速地处理用户提出的正当意见或投诉。投诉可提交至 ${CONTACT_EMAIL}，公司将尽力在收到后十四（14）日内回复。

（二）本条款及本服务的使用适用大韩民国法律，不适用冲突法规则。

（三）因本服务在公司与用户之间产生的诉讼，应向大韩民国《民事诉讼法》规定的管辖法院提起。用户为消费者的，本条任何内容均不剥夺其依据消费者保护强制性规定所享有的保护，包括在该等规定指定的法院起诉或应诉的权利。

（四）用户还可以通过韩国消费者院或电子交易纠纷调解委员会寻求救济；居住在欧盟的用户可以使用欧洲在线争议解决平台（https://ec.europa.eu/consumers/odr）。` },
				{ title: '附则', content: `（一）本条款自 ${EFFECTIVE_DATE} 起施行，最后修订于 ${LAST_UPDATED}。修订后的条款取代此前的所有版本。

（二）有关本条款的咨询，请联系 ${CONTACT_EMAIL}。

- **运营者**: ${COMPANY_NAME}
- **营业执照登记号**: ${BUSINESS_NUMBER}
- **通信销售业申报号**: ${ECOMMERCE_NUMBER}
- **地址**: ${COMPANY_ADDRESS_EN}
- **联系方式**: ${CONTACT_EMAIL}` }
			]
		}
	};

	$: t = content[lang] || content.en;
</script>

<svelte:head>
	<title>{t.title} - {SITE_NAME}</title>
	<meta name="description" content={t.intro.slice(0, 160)} />
</svelte:head>

<div class="max-w-4xl mx-auto px-4 py-12">
	<h1 class="text-3xl font-bold text-gray-900 dark:text-dark-100 mb-2">{t.title}</h1>
	<p class="text-gray-500 dark:text-dark-500 text-sm">{t.lastUpdated}</p>
	<p class="text-gray-500 dark:text-dark-500 text-sm mb-8">{t.effective}</p>

	<p class="text-gray-700 dark:text-dark-300 mb-8 leading-relaxed">{t.intro}</p>

	<div class="space-y-8">
		{#each t.sections as section}
			<section>
				<h2 class="text-xl font-semibold text-gray-900 dark:text-dark-100 mb-3">{section.title}</h2>
				<div class="text-gray-700 dark:text-dark-300 leading-relaxed whitespace-pre-line">
					{@html section.content.replace(/\*\*([^*]+)\*\*/g, '<strong class="text-gray-900 dark:text-dark-100">$1</strong>')}
				</div>
			</section>
		{/each}
	</div>

	<div class="mt-12 pt-8 border-t border-gray-200 dark:border-dark-700">
		<a href="/{lang}" class="text-primary-500 hover:text-primary-400 transition-colors">
			← {lang === 'ko' ? '홈으로 돌아가기' : lang === 'ja' ? 'ホームに戻る' : lang === 'zh' ? '返回首页' : 'Back to Home'}
		</a>
	</div>
</div>
